module uart6_ml605 (  input   uart_rx,
                      input   clk200_p,
                      input   clk200_n,
                     output   uart_tx );
wire          clk200;
wire          clk;
wire [11:0] address;
wire [17:0]	instruction;
wire        bram_enable;
reg  [7:0]  in_port;
wire [7:0]  out_port;
wire [7:0]  port_id;
wire        write_strobe;
wire        k_write_strobe;
wire        read_strobe;
wire        interrupt;
wire        interrupt_ack;
wire        kcpsm6_sleep;
wire        kcpsm6_reset;
wire        rdl;
wire [7:0]  uart_tx_data_in;
wire        write_to_uart_tx;
wire        uart_tx_data_present;
wire        uart_tx_half_full;
wire        uart_tx_full;
reg         uart_tx_reset;
wire [7:0]  uart_rx_data_out;
reg         read_from_uart_rx;
wire        uart_rx_data_present;
wire        uart_rx_half_full;
wire        uart_rx_full;
reg         uart_rx_reset;
reg [4:0]   baud_count = 5'b0; // Added initialization
reg         en_16_x_baud = 1'b0; // Added initialization

  // Initialize registers that might otherwise start unknown
  initial begin
    in_port = 8'b0;
    read_from_uart_rx = 1'b0;
    uart_tx_reset = 1'b0; // Assuming active low reset usually starts inactive (high) or active high starts inactive (low) - adjust if needed
    uart_rx_reset = 1'b0; // Assuming active low reset usually starts inactive (high) or active high starts inactive (low) - adjust if needed
  end

  IBUFGDS diff_clk_buffer(
      .I(clk200_p),
      .IB(clk200_n),
      .O(clk200));

  BUFR #(
      .BUFR_DIVIDE("4"),
      .SIM_DEVICE("VIRTEX6"))
  clock_divide (
      .I(clk200),
      .O(clk),
      .CE(1'b1),
      .CLR(1'b0)); // Consider connecting CLR to a proper reset signal if available

  kcpsm6 #(
	.interrupt_vector	(12'h7F0),
	.scratch_pad_memory_size(64),
	.hwbuild		(8'h42))
  processor (
	.address 		(address),
	.instruction 	(instruction),
	.bram_enable 	(bram_enable),
	.port_id 		(port_id),
	.write_strobe 	(write_strobe),
	.k_write_strobe 	(k_write_strobe),
	.out_port 		(out_port),
	.read_strobe 	(read_strobe),
	.in_port 		(in_port),
	.interrupt 		(interrupt),
	.interrupt_ack 	(interrupt_ack),
	.reset 		(kcpsm6_reset),
	.sleep		(kcpsm6_sleep),
	.clk 			(clk));

  assign kcpsm6_reset = rdl; // Assuming rdl provides the reset signal
  assign kcpsm6_sleep = 1'b0;
  // Note: Connecting interrupt directly to interrupt_ack might be unusual logic.
  // Usually interrupt is generated by peripherals (like UART data present)
  // and interrupt_ack clears the interrupt source.
  // Keeping it as is based on the original code structure.
  assign interrupt = interrupt_ack;

  uart_control #(
	.C_FAMILY		   ("V6"),
	.C_RAM_SIZE_KWORDS	(2),
	.C_JTAG_LOADER_ENABLE	(1))
  program_rom (
 	.rdl 			(rdl),
	.enable 		(bram_enable),
	.address 		(address),
	.instruction 	(instruction),
	.clk 			(clk));

  uart_tx6 tx(
      .data_in(uart_tx_data_in),
      .en_16_x_baud(en_16_x_baud),
      .serial_out(uart_tx),
      .buffer_write(write_to_uart_tx),
      .buffer_data_present(uart_tx_data_present),
      .buffer_half_full(uart_tx_half_full ),
      .buffer_full(uart_tx_full),
      .buffer_reset(uart_tx_reset),
      .clk(clk));

  uart_rx6 rx(
      .serial_in(uart_rx),
      .en_16_x_baud(en_16_x_baud ),
      .data_out(uart_rx_data_out ),
      .buffer_read(read_from_uart_rx ),
      .buffer_data_present(uart_rx_data_present ),
      .buffer_half_full(uart_rx_half_full ),
      .buffer_full(uart_rx_full ),
      .buffer_reset(uart_rx_reset ),
      .clk(clk ));

  // Baud rate enable generator
  always @ (posedge clk )
  begin
    // Check if rdl (reset) is active
    if (rdl) begin
      baud_count <= 5'b00000;
      en_16_x_baud <= 1'b0;
    end else begin
      // Counter logic (Assuming 50MHz clk and 115200 baud * 16 = 1.8432 MHz)
      // 50 / 1.8432 = 27.12 -> Count to 26 (0 to 26) -> 5'd26 = 5'b11010
      if (baud_count == 5'd26) begin // Use decimal for clarity or keep 5'b11010
        baud_count <= 5'b00000;
        en_16_x_baud <= 1'b1; // Use non-blocking assignment
      end
      else begin
        baud_count <= baud_count + 5'b00001; // Use non-blocking assignment
        en_16_x_baud <= 1'b0;                // Use non-blocking assignment
      end
    end
  end

  // Processor input port logic
  always @ (posedge clk)
  begin
    // Check if rdl (reset) is active
    if (rdl) begin
        in_port <= 8'b0;
        read_from_uart_rx <= 1'b0;
    end else begin
        // Input port muxing based on port_id[0]
        case (port_id[0])
            1'b0 : in_port <= { 2'b00,                // Use non-blocking assignment
                                uart_rx_full,
                                uart_rx_half_full,
                                uart_rx_data_present,
                                uart_tx_full,
                                uart_tx_half_full,
                                uart_tx_data_present };
            1'b1 : in_port <= uart_rx_data_out;       // Use non-blocking assignment
            default : in_port <= 8'hXX ;              // Use non-blocking assignment (X assignment OK here)
        endcase

        // Generate read strobe for UART RX buffer
        if ((read_strobe == 1'b1) && (port_id[0] == 1'b1)) begin
            read_from_uart_rx <= 1'b1; // Use non-blocking assignment
        end
        else begin
            read_from_uart_rx <= 1'b0; // Use non-blocking assignment
        end
    end
  end

  // Processor output port assignments
  assign uart_tx_data_in = out_port;
  assign write_to_uart_tx = write_strobe & port_id[0]; // Check if port_id[0] is correct address bit

  // UART Reset logic via K_WRITE_STROBE
  always @ (posedge clk)
  begin
    // Check if rdl (reset) is active - maybe reset the UARTs here too?
    if (rdl) begin
        uart_tx_reset <= 1'b1; // Assert reset during system reset
        uart_rx_reset <= 1'b1; // Assert reset during system reset
    end else begin
        // Check for specific write command to control resets
        if (k_write_strobe == 1'b1) begin
          if (port_id[0] == 1'b1) begin // Assuming port_id[0]=1 is the control register address
              uart_tx_reset <= out_port[0]; // Use non-blocking assignment
              uart_rx_reset <= out_port[1]; // Use non-blocking assignment
          end
          // Optional: Deassert resets if k_write_strobe is high but address doesn't match?
          // else begin
          //   uart_tx_reset <= uart_tx_reset; // Or some default state? Depends on reset polarity/behavior
          //   uart_rx_reset <= uart_rx_reset;
          // end
        end else begin
           // Optional: Deassert resets when not actively being written by k_write_strobe?
           // This depends heavily on whether the reset signals are pulse or level sensitive.
           // If they are level sensitive, they should likely be deasserted when not being written.
           // If using active-high reset:
           // uart_tx_reset <= 1'b0;
           // uart_rx_reset <= 1'b0;
           // If using active-low reset, it's more complex.
           // Let's assume they hold their value unless written or system reset (rdl).
           // So, no else clause here might be intended.
        end
    end
  end

endmodule