module rxtx( 
   input   wire            A2D_CLKn, 
   input   wire            A2D_CLKp, 
   input   wire            ADC_SYNC_INn, 
   input   wire            ADC_SYNC_INp, 
   input   wire            CH1_A2D_CLKn, 
   input   wire            CH1_A2D_CLKp, 
   input   wire    [6:0]   CH1_A2D_DATAn, 
   input   wire    [6:0]   CH1_A2D_DATAp, 
   input   wire            CH1_HV_OF, 
   input   wire            CH1_LV_OF, 
   input   wire            CH2_A2D_CLKn, 
   input   wire            CH2_A2D_CLKp, 
   input   wire    [6:0]   CH2_A2D_DATAn, 
   input   wire    [6:0]   CH2_A2D_DATAp, 
   input   wire            CH2_HV_OF, 
   input   wire            CH2_LV_OF, 
   input   wire            DAC_GDATACLKn, 
   input   wire            DAC_GDATACLKp, 
   input   wire            DAC_SYNC_INn, 
   input   wire            DAC_SYNC_INp, 
   input   wire            EXT_CLK_SDI, 
   input   wire            EXT_CLK_STATUS, 
   input   wire            LVCLK_200n, 
   input   wire            LVCLK_200p, 
   input   wire            MGT_REFCLK_n, 
   input   wire            MGT_REFCLK_p, 
   input   wire            PCIE_REFCLK_n, 
   input   wire            PCIE_REFCLK_p, 
   input   wire            PCIE_RESETn, 
   input   wire            TEMP_ALERTn, 
   input   wire            TEMP_THERMn,
   input   wire            sys_clk,  // Primary input clock
   output  wire            ADC_SYNC_DISABLEn, 
   output  wire            ADC_SYNC_DISABLEp, 
   output  wire            ADC_SYNC_OUTn, 
   output  wire            ADC_SYNC_OUTp, 
   output  wire            CH1_A2D_OE, 
   output  wire            CH1_A2D_RESET, 
   output  wire            CH1_A2D_SCLK, 
   output  wire            CH1_A2D_SDATA, 
   output  wire            CH1_A2D_SEN, 
   output  wire            CH2_A2D_OE, 
   output  wire            CH2_A2D_RESET, 
   output  wire            CH2_A2D_SCLK, 
   output  wire            CH2_A2D_SDATA, 
   output  wire            CH2_A2D_SEN, 
   output  wire            CPLD_CSn, 
   output  wire            CPLD_RSTn, 
   output  wire            DAC_CAL, 
   output  wire            DAC_CLKDIV, 
   output  wire    [11:0]  DAC_DAn, 
   output  wire    [11:0]  DAC_DAp, 
   output  wire    [11:0]  DAC_DBn, 
   output  wire    [11:0]  DAC_DBp, 
   output  wire    [11:0]  DAC_DCn, 
   output  wire    [11:0]  DAC_DCp, 
   output  wire    [11:0]  DAC_DDn, 
   output  wire    [11:0]  DAC_DDp, 
   output  wire            DAC_DELAY, 
   output  wire            DAC_RF, 
   output  wire            DAC_RZ, 
   output  wire            DAC_SYNC_DISABLEn, 
   output  wire            DAC_SYNC_DISABLEp, 
   output  wire            DAC_SYNC_OUTn, 
   output  wire            DAC_SYNC_OUTp, 
   output  wire            EXT_CLK_CSn, 
   output  wire            EXT_CLK_FUNC, 
   output  wire            EXT_CLK_SCLK, 
   output  wire            EXT_CLK_SDO, 
   output  wire            I2C_BUS_SELECT, 
   inout   wire            I2C_SCLK, 
   inout   wire            I2C_SDATA 
);

// ... existing code ...

clockControl clockControl1( 
   .A2D_CLKn            (A2D_CLKn), 
   .A2D_CLKp            (A2D_CLKp), 
   .DAC_GDATACLKn       (DAC_GDATACLKn), 
   .DAC_GDATACLKp       (DAC_GDATACLKp), 
   .LVCLK_200n          (LVCLK_200n), 
   .LVCLK_200p          (LVCLK_200p), 
   .MGT_REFCLK_n        (MGT_REFCLK_n), 
   .MGT_REFCLK_p        (MGT_REFCLK_p), 
   .PCIE_REFCLK_n       (PCIE_REFCLK_n), 
   .PCIE_REFCLK_p       (PCIE_REFCLK_p), 
   .sys_clk             (sys_clk),     // Use primary input clock
   .a2d_clk_reset       (a2d_clk_reset), 
   .dacClkLowFreqSelect (dacClkLowFreqSelect), 
   .dac_reset           (dac_reset), 
   .pll_reset           (pll_reset), 
   .user_clk            (user_clk), 
   .a2dClk              (a2dClk), 
   .a2d_clk_locked      (a2d_clk_locked), 
   .clk150Mhz           (clk150Mhz), 
   .clk200Mhz           (clk200Mhz), 
   .clk390KHz           (clk390KHz), 
   .dacClk              (dacClk), 
   .dac_clk_div2        (dac_clk_div2), 
   .dac_clk_locked      (dac_clk_locked), 
   .lcbClk              (lcbClk), 
   .lcb_clk_locked      (lcb_clk_locked), 
   .mgtRefClk           (mgtRefClk), 
   .pcie_ref_clk        (pcie_ref_clk), 
   .user_clk_div2       (user_clk_div2), 
   .user_clk_locked     (user_clk_locked)
);

// ... rest of existing code ...

endmodule