`default_nettype none
`default_nettype none
module plle2_test
(
input  wire         CLK,
input  wire         RST,
input  wire         I_CLKINSEL,
input  wire         test_i,      // Added DFT input
input  wire         test_clk_i,  // Added DFT input
output wire         O_LOCKED,
output wire [5:0]   O_CNT
);

wire clk100;
reg  clk50;
assign clk100 = CLK;

// This flop generates clk50. It's clocked by clk100 (derived from primary CLK). No reset. DFT compliant itself.
always @(posedge clk100)
    clk50 <= !clk50;

wire clk_fb_o;
wire clk_fb_i;
wire [5:0] clk; // Internal clocks generated by PLL

PLLE2_ADV #
(
.BANDWIDTH          ("HIGH"),
.COMPENSATION       ("BUF_IN"),
.CLKIN1_PERIOD      (20.0),
.CLKIN2_PERIOD      (10.0),
.CLKFBOUT_MULT      (16),
.CLKFBOUT_PHASE     (0.0),
.CLKOUT0_DIVIDE     (16),
.CLKOUT0_DUTY_CYCLE (0.53125),
.CLKOUT0_PHASE      (45.0),
.CLKOUT1_DIVIDE     (32),
.CLKOUT1_DUTY_CYCLE (0.5),
.CLKOUT1_PHASE      (90.0),
.CLKOUT2_DIVIDE     (48),
.CLKOUT2_DUTY_CYCLE (0.5),
.CLKOUT2_PHASE      (135.0),
.CLKOUT3_DIVIDE     (64),
.CLKOUT3_DUTY_CYCLE (0.5),
.CLKOUT3_PHASE      (-45.0),
.CLKOUT4_DIVIDE     (80),
.CLKOUT4_DUTY_CYCLE (0.5),
.CLKOUT4_PHASE      (-90.0),
.CLKOUT5_DIVIDE     (96),
.CLKOUT5_DUTY_CYCLE (0.5),
.CLKOUT5_PHASE      (-135.0),
.STARTUP_WAIT       ("FALSE")
)
pll
(
.CLKIN1     (clk50),        // Uses internally generated clk50
.CLKIN2     (clk100),       // Uses primary input derived clk100
.CLKINSEL   (I_CLKINSEL),
.RST        (RST),          // Primary input reset
.LOCKED     (O_LOCKED),     // Internal status signal
.CLKFBIN    (clk_fb_i),
.CLKFBOUT   (clk_fb_o),
.CLKOUT0    (clk[0]),       // Generated clocks
.CLKOUT1    (clk[1]),
.CLKOUT2    (clk[2]),
.CLKOUT3    (clk[3]),
.CLKOUT4    (clk[4]),
.CLKOUT5    (clk[5])
);

BUFG clk_fb_buf (.I(clk_fb_o), .O(clk_fb_i));

// Original reset logic: wire rst = RST || !O_LOCKED; -> ACNPCI violation

genvar i;
generate for (i=0; i<6; i=i+1) begin : counter_gen
  reg [23:0] counter;

  // DFT Fix: Mux clock and reset for testability
  wire rst_internal = RST || !O_LOCKED;             // Original functional reset logic
  wire rst_muxed = test_i ? RST : rst_internal;      // Select primary RST for async reset in test mode (ACNPCI Fix)
  wire clk_muxed = test_i ? test_clk_i : clk[i];    // Select test_clk_i in test mode (CLKNPI/FFCKNP Fix)

  // Flop using muxed clock and reset
  // Original was clocked by clk[i] (internal) -> CLKNPI violation
  // Original async reset by rst (internal O_LOCKED) -> ACNCPI violation
  always @(posedge clk_muxed or posedge rst_muxed) begin // Use muxed signals
      if (rst_muxed) begin
          counter <= 24'b0;
      end else begin
          counter <= counter + 1;
      end
  end

  assign O_CNT[i] = counter[21];
end endgenerate

endmodule
`default_nettype wire // Restore default net type