`timescale 1ps/1ps
`timescale 1ps/1ps
module clk_dll_exdes
 #(
  parameter TCQ = 100
  )
 (
  input         CLK_IN1,
  input         COUNTER_RESET,
  output [3:1]  CLK_OUT,
  output [3:1]  COUNT,
  input         RESET,
  output        LOCKED,
  // DFT Inputs
  input         test_i,
  input         test_clk_i
 );
  localparam    C_W       = 16;
  localparam    NUM_C     = 3;
  genvar        count_gen;

  // Original reset logic combined RESET, COUNTER_RESET and !LOCKED
  wire          reset_int_func = !LOCKED || RESET || COUNTER_RESET;

  // DFT controllable asynchronous reset (uses primary RESET in test mode)
  wire          dft_reset = test_i ? RESET : reset_int_func;

   reg [NUM_C:1] rst_sync;
   reg [NUM_C:1] rst_sync_int;
   reg [NUM_C:1] rst_sync_int1;
   reg [NUM_C:1] rst_sync_int2;
  wire [NUM_C:1] clk_int;
  wire [NUM_C:1] clk_n;
  wire [NUM_C:1] clk;
  reg [C_W-1:0]  counter [NUM_C:1];

  // DFT controllable clock
  wire [NUM_C:1] dft_clk;
  wire [NUM_C:1] dft_clk_n;


  clk_dll clknetwork
   (
    .clk50in            (CLK_IN1),
    .clk50           (clk_int[1]),
    .clk25           (clk_int[2]),
    .clk3p2           (clk_int[3]),
    .RESET              (RESET), // Functional reset to DLL
    .LOCKED             (LOCKED));


  assign clk[1] = clk_int[1];
  assign clk[2] = clk_int[2];
  assign clk[3] = clk_int[3];

genvar clk_out_pins;
generate
  for (clk_out_pins = 1; clk_out_pins <= NUM_C; clk_out_pins = clk_out_pins + 1)
  begin: gen_dft_clocks
    assign dft_clk[clk_out_pins] = test_i ? test_clk_i : clk[clk_out_pins];
    assign dft_clk_n[clk_out_pins] = ~dft_clk[clk_out_pins];
  end

  for (clk_out_pins = 1; clk_out_pins <= NUM_C; clk_out_pins = clk_out_pins + 1)
  begin: gen_outclk_oddr
  // assign clk_n[clk_out_pins] = ~clk[clk_out_pins]; // Original, not needed if using dft_clk_n
  ODDR2 clkout_oddr
   (.Q  (CLK_OUT[clk_out_pins]), // Corrected index
    .C0 (dft_clk[clk_out_pins]), // Use DFT muxed clock
    .C1 (dft_clk_n[clk_out_pins]), // Use inverted DFT muxed clock
    .CE (1'b1),
    .D0 (1'b1),
    .D1 (1'b0),
    .R  (1'b0), // Assuming tied off functionally, connect to DFT reset if needed
    .S  (1'b0)); // Assuming tied off functionally, connect to DFT reset if needed
  end
endgenerate


  // Reset Synchronization Logic - uses DFT clock and DFT reset
  generate for (count_gen = 1; count_gen <= NUM_C; count_gen = count_gen + 1) begin: counters_1
    // Using DFT controllable asynchronous reset and DFT controllable clock
    always @(posedge dft_reset or posedge dft_clk[count_gen]) begin
       if (dft_reset) begin // Async reset controlled by dft_reset
            rst_sync[count_gen] <= #TCQ 1'b1;
            rst_sync_int[count_gen]<= #TCQ 1'b1;
            rst_sync_int1[count_gen]<= #TCQ 1'b1;
            rst_sync_int2[count_gen]<= #TCQ 1'b1;
       end
       else begin // Clocked path using dft_clk
            rst_sync[count_gen] <= #TCQ 1'b0;
            rst_sync_int[count_gen] <= #TCQ rst_sync[count_gen];
            rst_sync_int1[count_gen] <= #TCQ rst_sync_int[count_gen];
            rst_sync_int2[count_gen] <= #TCQ rst_sync_int1[count_gen];
       end
    end
  end
  endgenerate

  // Counter Logic - uses DFT clock and synchronous reset derived from DFT-friendly sync chain
  generate for (count_gen = 1; count_gen <= NUM_C; count_gen = count_gen + 1) begin: counters
    // Changed asynchronous reset rst_sync_int2 to synchronous reset
    // Clocked by DFT controllable clock dft_clk
    always @(posedge dft_clk[count_gen]) begin
      // rst_sync_int2 is generated by DFT-friendly flops (dft_clk, dft_reset)
      // Using it as synchronous reset signal
      if (rst_sync_int2[count_gen]) begin
        counter[count_gen] <= #TCQ { C_W { 1'b 0 } };
      end else begin
        counter[count_gen] <= #TCQ counter[count_gen] + 1'b 1;
      end
    end
    assign COUNT[count_gen] = counter[count_gen][C_W-1];
  end
  endgenerate

endmodule