`timescale 1 ps / 1 ps
module multiSRC_onboard(
	input SYSCLK_N,
	input SYSCLK_P,
	input GPIO_SW_RIGHT,
	input GPIO_SW_CENTER,
    input test_i,         // Test mode enable
    input scan_clk,       // Scan clock input
    input scan_rst_n,     // Scan reset input (active low)
	output GPIO_LED_CENTER,
	output GPIO_LED_LEFT,
	output GPIO_LED_RIGHT
);
wire test_start;
wire test_done;       // Wire to connect TB output
wire test_pass;
wire clk;             // Functional clock from PLL
wire dft_clk;         // Muxed clock for DFT
wire rst;             // Functional reset (active high)
wire dft_rst;         // Muxed reset for DFT (active high)
wire dft_pll_reset;   // Muxed reset for PLL (active high)
reg [26:0] cnt;
wire locked;          // PLL lock signal

wire ap_start;        // Control signal from TB to DUT
wire ap_ready;        // Status signal from DUT to TB
wire ap_idle;         // Status signal from DUT to TB
wire ap_done;         // Status signal from DUT to TB
wire dut_rst_from_tb; // Reset signal generated by TB for DUT functional control
wire dut_actual_rst;  // Actual reset signal going into DUT (muxed)
wire vld_x;           // Data valid signal from TB to DUT
wire vld_y;           // Data valid signal from DUT to TB
wire [15:0] x;        // Data from TB to DUT
wire [2:0]  rat;      // Data from TB to DUT
wire [47:0] y;        // Data from DUT to TB


// DFT Clock Mux: Select scan clock in test mode, functional clock otherwise
assign dft_clk = test_i ? scan_clk : clk;

// Functional Reset Assignment (Assuming active-high reset internally from switch)
assign rst = GPIO_SW_CENTER;

// DFT Reset Mux (Active high): Select scan reset (inverted) in test mode, functional reset otherwise
// This reset controls the counter and is used as input for the DUT reset mux
assign dft_rst = test_i ? ~scan_rst_n : rst;

// DFT PLL Reset Mux (Active high): Controls the PLL reset pin
assign dft_pll_reset = test_i ? ~scan_rst_n : rst;

// Counter with DFT clock and DFT asynchronous reset (active high)
always @(posedge dft_clk, posedge dft_rst) begin
	if(dft_rst) begin
		cnt <= 27'b0;
	end else begin
		cnt <= cnt + 1'b1;
	end
end


assign test_start = GPIO_SW_RIGHT;
assign GPIO_LED_CENTER = test_pass;
assign GPIO_LED_RIGHT = cnt[26];
assign GPIO_LED_LEFT = locked;

// PLL Instance - Using muxed DFT reset for the PLL itself
// Ensure port names match the clk_wiz_0 module definition
clk_wiz_0 CLKPLL
 (
  .clk_in1_p(SYSCLK_P),
  .clk_in1_n(SYSCLK_N),
  .clk_out1(clk),          // Output functional clock
  .reset(dft_pll_reset),   // Use muxed DFT reset for PLL
  .locked(locked)
 );

// Test Bench Instance
// Ensure port names/directions match the test_bench_onboard module definition
// The TB itself uses the global DFT clock and reset for its internal FFs
test_bench_onboard TB
(
	.clk(dft_clk),           // Use DFT clock
	.rst(dft_rst),           // Use global DFT reset for TB internal logic
	.test_start(test_start), // Input from GPIO
	.test_done(test_done),   // Output from TB
	.test_pass(test_pass),   // Output from TB to LED
	.ap_ready(ap_ready),     // Input to TB from DUT
	.ap_idle(ap_idle),       // Input to TB from DUT
	.ap_done(ap_done),       // Input to TB from DUT
	.dut_vld_y(vld_y),     // Input to TB from DUT
	.dut_y(y),           // Input to TB from DUT
	.dut_rst(dut_rst_from_tb),// Output reset from TB (for functional control)
	.dut_start(ap_start),    // Output from TB to DUT
	.dut_vld_x(vld_x),     // Output from TB to DUT
	.dut_x(x),           // Output from TB to DUT
	.dut_rat(rat)        // Output from TB to DUT
);

// DUT Reset Mux: Select global DFT reset in test mode, TB-controlled reset otherwise
// This ensures the DUT reset is controllable from primary inputs during test
assign dut_actual_rst = test_i ? dft_rst : dut_rst_from_tb;

// DUT Instance
// Ensure port names/directions match the multiSRC module definition
multiSRC DUT(
        .ap_clk(dft_clk),        // Input DFT clock
        .ap_rst(dut_actual_rst), // Input muxed reset
        .ap_start(ap_start),     // Input start from TB
        .ap_done(ap_done),       // Output to TB
        .ap_idle(ap_idle),       // Output to TB
        .ap_ready(ap_ready),     // Output to TB
        .vld_i(vld_x),         // Input data valid from TB
        .x_i_V(x),           // Input data from TB
        .rat_i_V(rat),         // Input data from TB
        .vld_o(vld_y),         // Output data valid to TB
        .y_o_V(y)            // Output data to TB
);
endmodule