module multiSRC_onboard(
	input SYSCLK_N,
	input SYSCLK_P,
	input GPIO_SW_RIGHT,
	input GPIO_SW_CENTER,
    input test_i,
    input scan_clk,
    input scan_rst_n, // Added dedicated test reset input
	output GPIO_LED_CENTER,
	output GPIO_LED_LEFT,
	output GPIO_LED_RIGHT
);
wire test_start;
wire test_done;
wire test_pass;
wire clk;
wire dft_clk;
wire rst; // Functional reset
wire dft_rst; // Combined reset for DFT
reg [26:0] cnt;

// DFT Clock Mux
assign dft_clk = test_i ? scan_clk : clk;

// Functional Reset Assignment
assign rst = GPIO_SW_CENTER;

// DFT Reset Mux (Assuming active-high reset for components)
// Use dedicated scan reset (active high derived from scan_rst_n) in test mode,
// Use functional reset (rst) in functional mode.
assign dft_rst = test_i ? ~scan_rst_n : rst;

// Counter with DFT clock and DFT reset (asynchronous active high)
always @(posedge dft_clk, posedge dft_rst) begin
	if(dft_rst) begin
		cnt <= 27'b0;
	end else begin
		cnt <= cnt + 1'b1;
	end
end

wire ap_start;
wire ap_ready;
wire ap_idle;
wire ap_done;
wire dut_rst; // Reset signal going into DUT from TB
wire vld_x;
wire vld_y;
wire [15:0] x;
wire [2:0]  rat;
wire [47:0] y;
wire locked;

assign test_start=GPIO_SW_RIGHT;
assign GPIO_LED_CENTER=test_pass;
assign GPIO_LED_RIGHT=cnt[26];
assign GPIO_LED_LEFT=locked;

// PLL Instance - Generally, PLL reset is kept functional or handled specially.
// Using functional reset 'rst' here. DFT tools might require specific handling.
clk_wiz_0 CLKPLL
 (
  .clk_in1_p(SYSCLK_P),
  .clk_in1_n(SYSCLK_N),
  .clk_out1(clk),
  .reset(rst), // Using functional reset for PLL
  .locked(locked)
 );

// Test Bench Instance with DFT clock and DFT reset
test_bench_onboard TB
(
	.clk(dft_clk),
	.rst(dft_rst), // Use combined DFT reset
	.test_start(test_start),
	.test_done(test_done),
	.test_pass(test_pass),
	.ap_ready(ap_ready),
	.ap_idle(ap_idle),
	.ap_done(ap_done),
	.dut_vld_y(vld_y),
	.dut_y(y),
	.dut_rst(dut_rst), // This reset signal is generated by TB based on its inputs
	.dut_start(ap_start),
	.dut_vld_x(vld_x),
	.dut_x(x),
	.dut_rat(rat)
);

// DUT Instance with DFT clock. Reset comes from TB's dut_rst output.
// TB internally uses dft_rst, so dut_rst is controllable during test mode.
multiSRC DUT(
        .ap_clk(dft_clk),
        .ap_rst(dut_rst), // Reset controlled by TB, which uses dft_rst
        .ap_start(ap_start),
        .ap_done(ap_done),
        .ap_idle(ap_idle),
        .ap_ready(ap_ready),
        .vld_i(vld_x),
        .x_i_V(x),
        .rat_i_V(rat),
        .vld_o(vld_y),
        .y_o_V(y)
);
endmodule