module multiSRC_onboard(
	input SYSCLK_N,
	input SYSCLK_P,
	input GPIO_SW_RIGHT,
	input GPIO_SW_CENTER,
	output GPIO_LED_CENTER,
	output GPIO_LED_LEFT,
	output GPIO_LED_RIGHT,
    // DFT inputs
    input scan_en,
    input test_clk_i,
    input test_rst_i
);

// Internal functional signals
wire clk;
wire rst;
wire locked;

// DFT signals
wire dft_clk; // Multiplexed clock for scan/functional mode
wire top_rst; // Multiplexed reset for scan/functional mode

// Wires for TB/DUT communication
wire test_start;
wire test_done;
wire test_pass;
wire ap_start;
wire ap_ready;
wire ap_idle;
wire ap_done;
// wire dut_rst; // Removed: Reset generated by TB is bad DFT practice
wire vld_x;
wire vld_y;
wire [15:0] x;
wire [2:0]  rat;
wire [47:0] y;

// Counter register
reg [26:0] cnt;

// Functional reset derived from primary input
assign rst = GPIO_SW_CENTER;

// DFT clock selection: Use test clock in scan mode, functional clock otherwise
assign dft_clk = scan_en ? test_clk_i : clk;

// DFT reset selection: Use test reset in scan mode, functional reset otherwise
// This single reset source feeds all resettable components (cnt, TB, DUT)
assign top_rst = scan_en ? test_rst_i : rst;

// Counter logic using DFT clock and unified reset
// Assuming asynchronous reset based on sensitivity list and naming
always @(posedge dft_clk or posedge top_rst) begin
	if(top_rst) begin
		cnt <= 27'b0; // Ensure full reset width
	end else begin
		cnt <= cnt + 1'b1;
	end
end

// Test signals and LED assignments
assign test_start = GPIO_SW_RIGHT;
assign GPIO_LED_CENTER = test_pass; // Indicates test completion status
assign GPIO_LED_RIGHT = cnt[26];    // Example output driven by counter
assign GPIO_LED_LEFT = locked;      // PLL lock status

// PLL instantiation
// Uses functional reset (rst), output clock (clk) is bypassed by dft_clk in scan mode
clk_wiz_0 CLKPLL (
  .clk_in1_p(SYSCLK_P),
  .clk_in1_n(SYSCLK_N),
  .clk_out1(clk),    // Functional clock output
  .reset(rst),       // Use functional reset for PLL
  .locked(locked)
);

// Test Bench instantiation
// Uses DFT clock (dft_clk) and unified DFT reset (top_rst)
// Removed dut_rst output port connection
test_bench_onboard TB (
	.clk(dft_clk),
	.rst(top_rst),      // Use unified reset
	.test_start(test_start),
	.test_done(test_done),
	.test_pass(test_pass),
	.ap_ready(ap_ready),
	.ap_idle(ap_idle),
	.ap_done(ap_done),
	.dut_vld_y(vld_y),
	.dut_y(y),
	// .dut_rst(dut_rst), // Port connection removed, assuming port removed from TB module def
	.dut_start(ap_start),
	.dut_vld_x(vld_x),
	.dut_x(x),
	.dut_rat(rat)
);

// DUT instantiation
// Uses DFT clock (dft_clk) and unified DFT reset (top_rst)
multiSRC DUT (
    .ap_clk(dft_clk),      // Use DFT clock
    .ap_rst(top_rst),      // Use unified reset
    .ap_start(ap_start),
    .ap_done(ap_done),
    .ap_idle(ap_idle),
    .ap_ready(ap_ready),
    .vld_i(vld_x),
    .x_i_V(x),
    .rat_i_V(rat),
    .vld_o(vld_y),
    .y_o_V(y)
);

endmodule