`timescale 1ns / 1ps

module dram_inf
(
input clk156_25,
input reset156_25_n,
input sys_rst, // Assuming this is the primary asynchronous reset for DFT purposes if needed
input				c0_sys_clk_p,
input				c0_sys_clk_n,
input				c1_sys_clk_p,
input				c1_sys_clk_n,
input				clk_ref_p,
input				clk_ref_n,
inout [71:0]       c0_ddr3_dq,
inout [8:0]        c0_ddr3_dqs_n,
inout [8:0]        c0_ddr3_dqs_p,
output [15:0]     c0_ddr3_addr,
output [2:0]      c0_ddr3_ba,
output            c0_ddr3_ras_n,
output            c0_ddr3_cas_n,
output            c0_ddr3_we_n,
output            c0_ddr3_reset_n,
output[1:0]       c0_ddr3_ck_p,
output[1:0]       c0_ddr3_ck_n,
output[1:0]       c0_ddr3_cke,
output[1:0]       c0_ddr3_cs_n,
output[1:0]       c0_ddr3_odt,
output           c0_ui_clk, // Note: Generated by DDR IP; Clocking internal logic below with this can cause CLKNPI/FFCKNP
output           c0_init_calib_complete,
inout [71:0]      c1_ddr3_dq,
inout [8:0]       c1_ddr3_dqs_n,
inout [8:0]       c1_ddr3_dqs_p,
output [15:0]    c1_ddr3_addr,
output [2:0]     c1_ddr3_ba,
output           c1_ddr3_ras_n,
output           c1_ddr3_cas_n,
output           c1_ddr3_we_n,
output           c1_ddr3_reset_n,
output[1:0]      c1_ddr3_ck_p,
output[1:0]      c1_ddr3_ck_n,
output[1:0]      c1_ddr3_cke,
output[1:0]      c1_ddr3_cs_n,
output[1:0]      c1_ddr3_odt,
output           c1_ui_clk, // Note: Generated by DDR IP; Clocking internal logic below with this can cause CLKNPI/FFCKNP
output           c1_init_calib_complete,
input           ht_s_axis_read_cmd_tvalid,
output          ht_s_axis_read_cmd_tready,
input[71:0]     ht_s_axis_read_cmd_tdata,
output          ht_m_axis_read_sts_tvalid,
input           ht_m_axis_read_sts_tready,
output[7:0]     ht_m_axis_read_sts_tdata,
output[511:0]    ht_m_axis_read_tdata,
output[63:0]     ht_m_axis_read_tkeep,
output          ht_m_axis_read_tlast,
output          ht_m_axis_read_tvalid,
input           ht_m_axis_read_tready,
input           ht_s_axis_write_cmd_tvalid,
output          ht_s_axis_write_cmd_tready,
input[71:0]     ht_s_axis_write_cmd_tdata,
output          ht_m_axis_write_sts_tvalid,
input           ht_m_axis_write_sts_tready,
output[7:0]     ht_m_axis_write_sts_tdata,
input[511:0]     ht_s_axis_write_tdata,
input[63:0]      ht_s_axis_write_tkeep,
input           ht_s_axis_write_tlast,
input           ht_s_axis_write_tvalid,
output          ht_s_axis_write_tready,
input           vs_s_axis_read_cmd_tvalid,
output          vs_s_axis_read_cmd_tready,
input[71:0]     vs_s_axis_read_cmd_tdata,
output          vs_m_axis_read_sts_tvalid,
input           vs_m_axis_read_sts_tready,
output[7:0]     vs_m_axis_read_sts_tdata,
output[511:0]    vs_m_axis_read_tdata,
output[63:0]     vs_m_axis_read_tkeep,
output          vs_m_axis_read_tlast,
output          vs_m_axis_read_tvalid,
input           vs_m_axis_read_tready,
input           vs_s_axis_write_cmd_tvalid,
output          vs_s_axis_write_cmd_tready,
input[71:0]     vs_s_axis_write_cmd_tdata,
output          vs_m_axis_write_sts_tvalid,
input           vs_m_axis_write_sts_tready,
output[7:0]     vs_m_axis_write_sts_tdata,
input[511:0]     vs_s_axis_write_tdata,
input[63:0]      vs_s_axis_write_tkeep,
input            vs_s_axis_write_tlast,
input            vs_s_axis_write_tvalid,
output           vs_s_axis_write_tready
);

// Internal signals from DDR3 IP (Assume ddr3_0 and ddr3_1 instances exist)
// These are driven by the placeholder DDR IP instances below
wire                   c0_ui_clk_internal; // Internal wire for clock generated by ddr3_0
wire                   c0_ui_clk_sync_rst; // Driven by ddr3_0
wire                   c0_mmcm_locked;     // Driven by ddr3_0
wire                   c1_ui_clk_internal; // Internal wire for clock generated by ddr3_1
wire                   c1_ui_clk_sync_rst; // Driven by ddr3_1
wire                   c1_mmcm_locked;     // Driven by ddr3_1

// Assign internal clocks to output ports
assign c0_ui_clk = c0_ui_clk_internal;
assign c1_ui_clk = c1_ui_clk_internal;

// Reset Synchronization
wire reset156_25; // Use active high reset internally for synchronizer
assign reset156_25 = ~reset156_25_n; // Assuming reset156_25_n is the primary reset source

// Synchronizer for c0_ui_clk domain
reg c0_reset_sync0, c0_reset_sync1;
wire c0_aresetn_sync;
// CLKNPI/FFCKNP VIOLATION: c0_ui_clk_internal is generated by ddr3_0_inst, not a primary clock.
always @(posedge c0_ui_clk_internal) begin
    c0_reset_sync0 <= reset156_25; // Or use sys_rst if that's the intended global async reset
    c0_reset_sync1 <= c0_reset_sync0;
end
assign c0_aresetn_sync = ~c0_reset_sync1; // Active low output

// Synchronizer for c1_ui_clk domain
reg c1_reset_sync0, c1_reset_sync1;
wire c1_aresetn_sync;
// CLKNPI/FFCKNP VIOLATION: c1_ui_clk_internal is generated by ddr3_1_inst, not a primary clock.
always @(posedge c1_ui_clk_internal) begin
    c1_reset_sync0 <= reset156_25; // Or use sys_rst
    c1_reset_sync1 <= c1_reset_sync0;
end
assign c1_aresetn_sync = ~c1_reset_sync1; // Active low output


// AXI Interface signals between datamovers and DDR IPs (driven/used by datamovers)
wire  [4:0]            c0_s_axi_awid;
wire  [32:0]           c0_s_axi_awaddr; // 33 bits
wire  [7:0]            c0_s_axi_awlen;
wire  [2:0]            c0_s_axi_awsize;
wire  [1:0]            c0_s_axi_awburst;
wire                   c0_s_axi_awvalid;
wire                   c0_s_axi_awready; // Driven by DDR IP AXI Slave Interface
wire  [511:0]          c0_s_axi_wdata;
wire  [63:0]           c0_s_axi_wstrb;
wire                   c0_s_axi_wlast;
wire                   c0_s_axi_wvalid;
wire                   c0_s_axi_wready; // Driven by DDR IP AXI Slave Interface
wire [4:0]             c0_s_axi_bid;    // Driven by DDR IP AXI Slave Interface
wire [1:0]             c0_s_axi_bresp;  // Driven by DDR IP AXI Slave Interface
wire                   c0_s_axi_bvalid; // Driven by DDR IP AXI Slave Interface
wire                   c0_s_axi_bready;
wire  [4:0]           c0_s_axi_arid;
wire  [32:0]          c0_s_axi_araddr; // 33 bits
wire  [7:0]           c0_s_axi_arlen;
wire  [2:0]           c0_s_axi_arsize;
wire  [1:0]           c0_s_axi_arburst;
wire                  c0_s_axi_arvalid;
wire                  c0_s_axi_arready; // Driven by DDR IP AXI Slave Interface
wire [4:0]       c0_s_axi_rid;     // Driven by DDR IP AXI Slave Interface
wire [511:0]     c0_s_axi_rdata;   // Driven by DDR IP AXI Slave Interface
wire [1:0]       c0_s_axi_rresp;   // Driven by DDR IP AXI Slave Interface
wire             c0_s_axi_rlast;   // Driven by DDR IP AXI Slave Interface
wire             c0_s_axi_rvalid;  // Driven by DDR IP AXI Slave Interface
wire             c0_s_axi_rready;

wire [4:0]      c1_s_axi_awid;
wire [32:0]     c1_s_axi_awaddr; // 33 bits
wire [7:0]      c1_s_axi_awlen;
wire [2:0]      c1_s_axi_awsize;
wire [1:0]      c1_s_axi_awburst;
wire            c1_s_axi_awvalid;
wire            c1_s_axi_awready; // Driven by DDR IP AXI Slave Interface
wire [511:0]    c1_s_axi_wdata;
wire [63:0]     c1_s_axi_wstrb;
wire            c1_s_axi_wlast;
wire            c1_s_axi_wvalid;
wire            c1_s_axi_wready; // Driven by DDR IP AXI Slave Interface
wire [4:0]      c1_s_axi_bid;    // Driven by DDR IP AXI Slave Interface
wire [1:0]      c1_s_axi_bresp;  // Driven by DDR IP AXI Slave Interface
wire            c1_s_axi_bvalid; // Driven by DDR IP AXI Slave Interface
wire            c1_s_axi_bready;
wire [4:0]      c1_s_axi_arid;
wire [32:0]     c1_s_axi_araddr; // 33 bits
wire [7:0]      c1_s_axi_arlen;
wire [2:0]      c1_s_axi_arsize;
wire [1:0]      c1_s_axi_arburst;
wire            c1_s_axi_arvalid;
wire            c1_s_axi_arready; // Driven by DDR IP AXI Slave Interface
wire [4:0]      c1_s_axi_rid;     // Driven by DDR IP AXI Slave Interface
wire [511:0]    c1_s_axi_rdata;   // Driven by DDR IP AXI Slave Interface
wire [1:0]      c1_s_axi_rresp;   // Driven by DDR IP AXI Slave Interface
wire            c1_s_axi_rlast;   // Driven by DDR IP AXI Slave Interface
wire            c1_s_axi_rvalid;  // Driven by DDR IP AXI Slave Interface
wire            c1_s_axi_rready;

// Placeholder for DDR3 IP Core 0 (Generates c0_ui_clk_internal, etc.)
// Assuming a module named 'ddr3_core' exists
ddr3_core ddr3_0_inst (
  .sys_clk_p(c0_sys_clk_p), .sys_clk_n(c0_sys_clk_n),
  .clk_ref_p(clk_ref_p), .clk_ref_n(clk_ref_n),
  .sys_rst(sys_rst), // Or appropriate reset like ~reset156_25_n
  .dq(c0_ddr3_dq), .dqs_n(c0_ddr3_dqs_n), .dqs_p(c0_ddr3_dqs_p),
  .addr(c0_ddr3_addr), .ba(c0_ddr3_ba), .ras_n(c0_ddr3_ras_n),
  .cas_n(c0_ddr3_cas_n), .we_n(c0_ddr3_we_n), .reset_n(c0_ddr3_reset_n),
  .ck_p(c0_ddr3_ck_p), .ck_n(c0_ddr3_ck_n), .cke(c0_ddr3_cke),
  .cs_n(c0_ddr3_cs_n), .odt(c0_ddr3_odt),
  .ui_clk(c0_ui_clk_internal), // Output clock from IP
  .ui_clk_sync_rst(c0_ui_clk_sync_rst), // Output sync reset from IP
  .mmcm_locked(c0_mmcm_locked),         // Output lock status from IP
  .init_calib_complete(c0_init_calib_complete),
  // AXI Slave Interface
  .s_axi_aclk(c0_ui_clk_internal), // AXI clock input for IP
  .s_axi_aresetn(c0_aresetn_sync), // AXI reset input for IP
  .s_axi_awid(c0_s_axi_awid), .s_axi_awaddr(c0_s_axi_awaddr), .s_axi_awlen(c0_s_axi_awlen),
  .s_axi_awsize(c0_s_axi_awsize), .s_axi_awburst(c0_s_axi_awburst), .s_axi_awvalid(c0_s_axi_awvalid),
  .s_axi_awready(c0_s_axi_awready), // Output from IP
  .s_axi_wdata(c0_s_axi_wdata), .s_axi_wstrb(c0_s_axi_wstrb), .s_axi_wlast(c0_s_axi_wlast),
  .s_axi_wvalid(c0_s_axi_wvalid), .s_axi_wready(c0_s_axi_wready), // Output from IP
  .s_axi_bid(c0_s_axi_bid), .s_axi_bresp(c0_s_axi_bresp), .s_axi_bvalid(c0_s_axi_bvalid), // Output from IP
  .s_axi_bready(c0_s_axi_bready),
  .s_axi_arid(c0_s_axi_arid), .s_axi_araddr(c0_s_axi_araddr), .s_axi_arlen(c0_s_axi_arlen),
  .s_axi_arsize(c0_s_axi_arsize), .s_axi_arburst(c0_s_axi_arburst), .s_axi_arvalid(c0_s_axi_arvalid),
  .s_axi_arready(c0_s_axi_arready), // Output from IP
  .s_axi_rid(c0_s_axi_rid), .s_axi_rdata(c0_s_axi_rdata), .s_axi_rresp(c0_s_axi_rresp), // Output from IP
  .s_axi_rlast(c0_s_axi_rlast), .s_axi_rvalid(c0_s_axi_rvalid), // Output from IP
  .s_axi_rready(c0_s_axi_rready)
);

// Placeholder for DDR3 IP Core 1 (Generates c1_ui_clk_internal, etc.)
// Assuming a module named 'ddr3_core' exists
ddr3_core ddr3_1_inst (
  .sys_clk_p(c1_sys_clk_p), .sys_clk_n(c1_sys_clk_n),
  .clk_ref_p(clk_ref_p), .clk_ref_n(clk_ref_n),
  .sys_rst(sys_rst), // Or appropriate reset like ~reset156_25_n
  .dq(c1_ddr3_dq), .dqs_n(c1_ddr3_dqs_n), .dqs_p(c1_ddr3_dqs_p),
  .addr(c1_ddr3_addr), .ba(c1_ddr3_ba), .ras_n(c1_ddr3_ras_n),
  .cas_n(c1_ddr3_cas_n), .we_n(c1_ddr3_we_n), .reset_n(c1_ddr3_reset_n),
  .ck_p(c1_ddr3_ck_p), .ck_n(c1_ddr3_ck_n), .cke(c1_ddr3_cke),
  .cs_n(c1_ddr3_cs_n), .odt(c1_ddr3_odt),
  .ui_clk(c1_ui_clk_internal), // Output clock from IP
  .ui_clk_sync_rst(c1_ui_clk_sync_rst), // Output sync reset from IP
  .mmcm_locked(c1_mmcm_locked),         // Output lock status from IP
  .init_calib_complete(c1_init_calib_complete),
  // AXI Slave Interface
  .s_axi_aclk(c1_ui_clk_internal), // AXI clock input for IP
  .s_axi_aresetn(c1_aresetn_sync), // AXI reset input for IP
  .s_axi_awid(c1_s_axi_awid), .s_axi_awaddr(c1_s_axi_awaddr), .s_axi_awlen(c1_s_axi_awlen),
  .s_axi_awsize(c1_s_axi_awsize), .s_axi_awburst(c1_s_axi_awburst), .s_axi_awvalid(c1_s_axi_awvalid),
  .s_axi_awready(c1_s_axi_awready), // Output from IP
  .s_axi_wdata(c1_s_axi_wdata), .s_axi_wstrb(c1_s_axi_wstrb), .s_axi_wlast(c1_s_axi_wlast),
  .s_axi_wvalid(c1_s_axi_wvalid), .s_axi_wready(c1_s_axi_wready), // Output from IP
  .s_axi_bid(c1_s_axi_bid), .s_axi_bresp(c1_s_axi_bresp), .s_axi_bvalid(c1_s_axi_bvalid), // Output from IP
  .s_axi_bready(c1_s_axi_bready),
  .s_axi_arid(c1_s_axi_arid), .s_axi_araddr(c1_s_axi_araddr), .s_axi_arlen(c1_s_axi_arlen),
  .s_axi_arsize(c1_s_axi_arsize), .s_axi_arburst(c1_s_axi_arburst), .s_axi_arvalid(c1_s_axi_arvalid),
  .s_axi_arready(c1_s_axi_arready), // Output from IP
  .s_axi_rid(c1_s_axi_rid), .s_axi_rdata(c1_s_axi_rdata), .s_axi_rresp(c1_s_axi_rresp), // Output from IP
  .s_axi_rlast(c1_s_axi_rlast), .s_axi_rvalid(c1_s_axi_rvalid), // Output from IP
  .s_axi_rready(c1_s_axi_rready)
);

// Placeholder for HT Datamover (Connects ht_* streams to c0_s_axi_*)
// Assuming a module named 'ht_datamover' exists
ht_datamover ht_datamover_inst (
    .clk(c0_ui_clk_internal), // CLKNPI violation source
    .reset_n(c0_aresetn_sync),

    // AXI Stream Slave (Read Command)
    .s_axis_read_cmd_tvalid(ht_s_axis_read_cmd_tvalid),
    .s_axis_read_cmd_tready(ht_s_axis_read_cmd_tready),
    .s_axis_read_cmd_tdata(ht_s_axis_read_cmd_tdata),

    // AXI Stream Master (Read Status)
    .m_axis_read_sts_tvalid(ht_m_axis_read_sts_tvalid),
    .m_axis_read_sts_tready(ht_m_axis_read_sts_tready),
    .m_axis_read_sts_tdata(ht_m_axis_read_sts_tdata),

    // AXI Stream Master (Read Data)
    .m_axis_read_tdata(ht_m_axis_read_tdata),
    .m_axis_read_tkeep(ht_m_axis_read_tkeep),
    .m_axis_read_tlast(ht_m_axis_read_tlast),
    .m_axis_read_tvalid(ht_m_axis_read_tvalid),
    .m_axis_read_tready(ht_m_axis_read_tready),

    // AXI Stream Slave (Write Command)
    .s_axis_write_cmd_tvalid(ht_s_axis_write_cmd_tvalid),
    .s_axis_write_cmd_tready(ht_s_axis_write_cmd_tready),
    .s_axis_write_cmd_tdata(ht_s_axis_write_cmd_tdata),

    // AXI Stream Master (Write Status)
    .m_axis_write_sts_tvalid(ht_m_axis_write_sts_tvalid),
    .m_axis_write_sts_tready(ht_m_axis_write_sts_tready),
    .m_axis_write_sts_tdata(ht_m_axis_write_sts_tdata),

    // AXI Stream Slave (Write Data)
    .s_axis_write_tdata(ht_s_axis_write_tdata),
    .s_axis_write_tkeep(ht_s_axis_write_tkeep),
    .s_axis_write_tlast(ht_s_axis_write_tlast),
    .s_axis_write_tvalid(ht_s_axis_write_tvalid),
    .s_axis_write_tready(ht_s_axis_write_tready),

    // AXI Master Interface (Connected to DDR IP 0)
    .m_axi_awid(c0_s_axi_awid),
    .m_axi_awaddr(c0_s_axi_awaddr),
    .m_axi_awlen(c0_s_axi_awlen),
    .m_axi_awsize(c0_s_axi_awsize),
    .m_axi_awburst(c0_s_axi_awburst),
    .m_axi_awvalid(c0_s_axi_awvalid),
    .m_axi_awready(c0_s_axi_awready),
    .m_axi_wdata(c0_s_axi_wdata),
    .m_axi_wstrb(c0_s_axi_wstrb),
    .m_axi_wlast(c0_s_axi_wlast),
    .m_axi_wvalid(c0_s_axi_wvalid),
    .m_axi_wready(c0_s_axi_wready),
    .m_axi_bid(c0_s_axi_bid),
    .m_axi_bresp(c0_s_axi_bresp),
    .m_axi_bvalid(c0_s_axi_bvalid),
    .m_axi_bready(c0_s_axi_bready),
    .m_axi_arid(c0_s_axi_arid),
    .m_axi_araddr(c0_s_axi_araddr),
    .m_axi_arlen(c0_s_axi_arlen),
    .m_axi_arsize(c0_s_axi_arsize),
    .m_axi_arburst(c0_s_axi_arburst),
    .m_axi_arvalid(c0_s_axi_arvalid),
    .m_axi_arready(c0_s_axi_arready),
    .m_axi_rid(c0_s_axi_rid),
    .m_axi_rdata(c0_s_axi_rdata),
    .m_axi_rresp(c