`timescale 1ns / 1ps

module pcie_compiler_0 (
                          input wire test_mode_i, // Added for DFT
                          input wire AvlClk_i,
                          input wire [ 11: 0] CraAddress_i,
                          input wire [  3: 0] CraByteEnable_i,
                          input wire         CraChipSelect_i,
                          input wire         CraRead,
                          input wire         CraWrite,
                          input wire [ 31: 0] CraWriteData_i,
                          input wire [  5: 0] RxmIrqNum_i,
                          input wire         RxmIrq_i,
                          input wire         RxmReadDataValid_i,
                          input wire [ 63: 0] RxmReadData_i,
                          input wire         RxmWaitRequest_i,
                          input wire [ 21: 0] TxsAddress_i,
                          input wire [  9: 0] TxsBurstCount_i,
                          input wire [  7: 0] TxsByteEnable_i,
                          input wire         TxsChipSelect_i,
                          input wire         TxsRead_i,
                          input wire [ 63: 0] TxsWriteData_i,
                          input wire         TxsWrite_i,
                          input wire         busy_altgxb_reconfig,
                          input wire         cal_blk_clk,
                          input wire         fixedclk_serdes,
                          input wire         gxb_powerdown,
                          input wire         pcie_rstn,
                          input wire         phystatus_ext,
                          input wire         pipe_mode,
                          input wire         pll_powerdown,
                          input wire         reconfig_clk,
                          input wire [  3: 0] reconfig_togxb,
                          input wire         refclk,
                          input wire         reset_n,
                          input wire         rx_in0,
                          input wire [  7: 0] rxdata0_ext,
                          input wire         rxdatak0_ext,
                          input wire         rxelecidle0_ext,
                          input wire [  2: 0] rxstatus0_ext,
                          input wire         rxvalid0_ext,
                          input wire [ 39: 0] test_in,

                          output wire        CraIrq_o,
                          output wire [ 31: 0] CraReadData_o,
                          output wire        CraWaitRequest_o,
                          output wire [ 31: 0] RxmAddress_o,
                          output wire [  9: 0