`timescale 1ns / 1ps

module mem_inf #(
    parameter C0_SIMULATION          =  "FALSE",
    parameter C1_SIMULATION           = "FALSE",
    parameter C0_SIM_BYPASS_INIT_CAL  = "OFF",
    parameter C1_SIM_BYPASS_INIT_CAL = "OFF",
    // Added AXI parameters (adjust if needed, these are examples)
    parameter C0_C_S_AXI_ID_WIDTH = 4,
    parameter C0_C_S_AXI_ADDR_WIDTH = 33,
    parameter C0_C_S_AXI_DATA_WIDTH = 512,
    parameter C0_C_S_AXI_CTRL_ADDR_WIDTH = 32,
    parameter C0_C_S_AXI_CTRL_DATA_WIDTH = 32,
    parameter C1_C_S_AXI_ID_WIDTH = 4,
    parameter C1_C_S_AXI_ADDR_WIDTH = 33,
    parameter C1_C_S_AXI_DATA_WIDTH = 512,
    parameter C1_C_S_AXI_CTRL_ADDR_WIDTH = 32,
    parameter C1_C_S_AXI_CTRL_DATA_WIDTH = 32
)
(
input               test_i, // Added for DFT
input               clk156_25, // Primary clock for DFT mux
input               reset156_25_n, // Primary async reset for synchronizers (Active Low)
inout [71:0]        c0_ddr3_dq,
inout [8:0]         c0_ddr3_dqs_n,
inout [8:0]         c0_ddr3_dqs_p,
output [15:0]       c0_ddr3_addr,
output [2:0]        c0_ddr3_ba,
output              c0_ddr3_ras_n,
output              c0_ddr3_cas_n,
output              c0_ddr3_we_n,
output              c0_ddr3_reset_n,
output [1:0]        c0_ddr3_ck_p,
output [1:0]        c0_ddr3_ck_n,
output [1:0]        c0_ddr3_cke,
output [1:0]        c0_ddr3_cs_n,
output [1:0]        c0_ddr3_odt,
output              c0_ui_clk, // Generated by MIG C0
output              c0_init_calib_complete,
input               c0_sys_clk_p, // MIG C0 System Clock Input P
input               c0_sys_clk_n, // MIG C0 System Clock Input N
input               clk_ref_p,    // MIG Reference Clock Input P (Shared)
input               clk_ref_n,    // MIG Reference Clock Input N (Shared)
input               c1_sys_clk_p, // MIG C1 System Clock Input P
input               c1_sys_clk_n, // MIG C1 System Clock Input N
input               sys_rst,      // System Reset Input (Active High) - Functional Reset
inout [71:0]        c1_ddr3_dq,
inout [8:0]         c1_ddr3_dqs_n,
inout [8:0]         c1_ddr3_dqs_p,
output [15:0]       c1_ddr3_addr,
output [2:0]        c1_ddr3_ba,
output              c1_ddr3_ras_n,
output              c1_ddr3_cas_n,
output              c1_ddr3_we_n,
output              c1_ddr3_reset_n,
output [1:0]        c1_ddr3_ck_p,
output [1:0]        c1_ddr3_ck_n,
output [1:0]        c1_ddr3_cke,
output [1:0]        c1_ddr3_cs_n,
output [1:0]        c1_ddr3_odt,
output              c1_ui_clk, // Generated by MIG C1
output              c1_init_calib_complete,
// AXI Interfaces (External facing, tied off internally)
// TOE TX Read
input               toeTX_s_axis_read_cmd_tvalid,
output              toeTX_s_axis_read_cmd_tready, // Tied low
input[71:0]         toeTX_s_axis_read_cmd_tdata,
output              toeTX_m_axis_read_sts_tvalid, // Tied low
input               toeTX_m_axis_read_sts_tready,
output[7:0]         toeTX_m_axis_read_sts_tdata, // Tied low
output[63:0]        toeTX_m_axis_read_tdata,     // Tied low
output[7:0]         toeTX_m_axis_read_tkeep,     // Tied low
output              toeTX_m_axis_read_tlast,     // Tied low
output              toeTX_m_axis_read_tvalid,    // Tied low
input               toeTX_m_axis_read_tready,
// TOE TX Write
input               toeTX_s_axis_write_cmd_tvalid,
output              toeTX_s_axis_write_cmd_tready, // Tied low
input[71:0]         toeTX_s_axis_write_cmd_tdata,
output              toeTX_m_axis_write_sts_tvalid, // Tied low
input               toeTX_m_axis_write_sts_tready,
output[7:0]        toeTX_m_axis_write_sts_tdata,  // Tied low
input[63:0]         toeTX_s_axis_write_tdata,
input[7:0]          toeTX_s_axis_write_tkeep,
input               toeTX_s_axis_write_tlast,
input               toeTX_s_axis_write_tvalid,
output              toeTX_s_axis_write_tready,     // Tied low
// TOE RX Read
input               toeRX_s_axis_read_cmd_tvalid,
output              toeRX_s_axis_read_cmd_tready, // Tied low
input[71:0]         toeRX_s_axis_read_cmd_tdata,
output              toeRX_m_axis_read_sts_tvalid, // Tied low
input               toeRX_m_axis_read_sts_tready,
output[7:0]         toeRX_m_axis_read_sts_tdata, // Tied low
output[63:0]        toeRX_m_axis_read_tdata,     // Tied low
output[7:0]         toeRX_m_axis_read_tkeep,     // Tied low
output              toeRX_m_axis_read_tlast,     // Tied low
output              toeRX_m_axis_read_tvalid,    // Tied low
input               toeRX_m_axis_read_tready,
// TOE RX Write
input               toeRX_s_axis_write_cmd_tvalid,
output              toeRX_s_axis_write_cmd_tready, // Tied low
input[71:0]         toeRX_s_axis_write_cmd_tdata,
output              toeRX_m_axis_write_sts_tvalid, // Tied low
input               toeRX_m_axis_write_sts_tready,
output[7:0]        toeRX_m_axis_write_sts_tdata,  // Tied low
input[63:0]         toeRX_s_axis_write_tdata,
input[7:0]          toeRX_s_axis_write_tkeep,
input               toeRX_s_axis_write_tlast,
input               toeRX_s_axis_write_tvalid,
output              toeRX_s_axis_write_tready,     // Tied low
// HT Read
input               ht_s_axis_read_cmd_tvalid,
output              ht_s_axis_read_cmd_tready,   // Tied low
input[71:0]         ht_s_axis_read_cmd_tdata,
output              ht_m_axis_read_sts_tvalid,   // Tied low
input               ht_m_axis_read_sts_tready,
output[7:0]         ht_m_axis_read_sts_tdata,    // Tied low
output[511:0]       ht_m_axis_read_tdata,        // Tied low
output[63:0]        ht_m_axis_read_tkeep,        // Tied low
output              ht_m_axis_read_tlast,        // Tied low
output              ht_m_axis_read_tvalid,       // Tied low
input               ht_m_axis_read_tready,
// HT Write
input               ht_s_axis_write_cmd_tvalid,
output              ht_s_axis_write_cmd_tready,  // Tied low
input[71:0]         ht_s_axis_write_cmd_tdata,
output              ht_m_axis_write_sts_tvalid,  // Tied low
input               ht_m_axis_write_sts_tready,
output[7:0]        ht_m_axis_write_sts_tdata,   // Tied low
input[511:0]        ht_s_axis_write_tdata,
input[63:0]         ht_s_axis_write_tkeep,
input               ht_s_axis_write_tlast,
input               ht_s_axis_write_tvalid,
output              ht_s_axis_write_tready,      // Tied low
// UPD Read
input               upd_s_axis_read_cmd_tvalid,
output              upd_s_axis_read_cmd_tready,  // Tied low
input[71:0]         upd_s_axis_read_cmd_tdata,
output              upd_m_axis_read_sts_tvalid,  // Tied low
input               upd_m_axis_read_sts_tready,
output[7:0]         upd_m_axis_read_sts_tdata,   // Tied low
output[511:0]       upd_m_axis_read_tdata,       // Tied low
output[63:0]        upd_m_axis_read_tkeep,       // Tied low
output              upd_m_axis_read_tlast,        // Tied low
output              upd_m_axis_read_tvalid,       // Tied low
input               upd_m_axis_read_tready,
// UPD Write
input               upd_s_axis_write_cmd_tvalid,
output              upd_s_axis_write_cmd_tready, // Tied low
input[71:0]         upd_s_axis_write_cmd_tdata,
output              upd_m_axis_write_sts_tvalid, // Tied low
input               upd_m_axis_write_sts_tready,
output[7:0]        upd_m_axis_write_sts_tdata,  // Tied low
input[511:0]        upd_s_axis_write_tdata,
input[63:0]         upd_s_axis_write_tkeep,
input               upd_s_axis_write_tlast,
input               upd_s_axis_write_tvalid,
output              upd_s_axis_write_tready      // Tied low
);

// Internal signals
wire                                    c0_ui_clk_sync_rst; // MIG Output
wire                                    c0_mmcm_locked;     // MIG Output
wire                                    c0_aresetn;         // Synchronized reset for MIG C0 (Active Low)
wire                                    c1_ui_clk_sync_rst; // MIG Output
wire                                    c1_mmcm_locked;     // MIG Output
wire                                    c1_aresetn;         // Synchronized reset for MIG C1 (Active Low)

// DFT Muxed Clocks for synchronizers
wire dft_c0_ui_clk = test_i ? clk156_25 : c0_ui_clk;
wire dft_c1_ui_clk = test_i ? clk156_25 : c1_ui_clk;

// C0 Reset Synchronizer (Input: sys_rst (Active High), Output: c0_aresetn (Active Low))
// Uses primary async reset reset156_25_n and DFT muxed clock dft_c0_ui_clk
reg c0_sys_rst_sync1, c0_sys_rst_sync2;
always @(posedge dft_c0_ui_clk or negedge reset156_25_n) begin // Async reset from primary input
  if (!reset156_25_n) begin
    c0_sys_rst_sync1 <= 1'b1; // Reset to inactive state for sys_rst
    c0_sys_rst_sync2 <= 1'b1;
  end else begin
    c0_sys_rst_sync1 <= sys_rst; // Capture functional reset
    c0_sys_rst_sync2 <= c0_sys_rst_sync1; // Synchronize
  end
end
assign c0_aresetn = ~c0_sys_rst_sync2; // Invert sync'd functional reset for MIG active low input

// C1 Reset Synchronizer (Input: sys_rst (Active High), Output: c1_aresetn (Active Low))
// Uses primary async reset reset156_25_n and DFT muxed clock dft_c1_ui_clk
reg c1_sys_rst_sync1, c1_sys_rst_sync2;
always @(posedge dft_c1_ui_clk or negedge reset156_25_n) begin // Async reset from primary input
  if (!reset156_25_n) begin
    c1_sys_rst_sync1 <= 1'b1; // Reset to inactive state for sys_rst
    c1_sys_rst_sync2 <= 1'b1;
  end else begin
    c1_sys_rst_sync1 <= sys_rst; // Capture functional reset
    c1_sys_rst_sync2 <= c1_sys_rst_sync1; // Synchronize
  end
end
assign c1_aresetn = ~c1_sys_rst_sync2; // Invert sync'd functional reset for MIG active low input


// MIG C0 AXI signals (wires) - Assume connected to mig_7series_0 instance
wire [C0_C_S_AXI_ID_WIDTH-1:0]          c0_s_axi_awid;
wire [C0_C_S_AXI_ADDR_WIDTH-1:0]        c0_s_axi_awaddr;
wire [7:0]                              c0_s_axi_awlen;
wire [2:0]                              c0_s_axi_awsize;
wire [1:0]                              c0_s_axi_awburst;
wire                                    c0_s_axi_awlock;
wire [3:0]                              c0_s_axi_awcache;
wire [2:0]                              c0_s_axi_awprot;
wire [3:0]                              c0_s_axi_awqos; // Typically 4-bit
wire [3:0]                              c0_s_axi_awregion; // Typically 4-bit
wire                                    c0_s_axi_awvalid;
wire                                    c0_s_axi_awready;
wire [C0_C_S_AXI_DATA_WIDTH-1:0]        c0_s_axi_wdata;
wire [(C0_C_S_AXI_DATA_WIDTH/8)-1:0]    c0_s_axi_wstrb;
wire                                    c0_s_axi_wlast;
wire                                    c0_s_axi_wvalid;
wire                                    c0_s_axi_wready;
wire                                    c0_s_axi_bready;
wire [C0_C_S_AXI_ID_WIDTH-1:0]          c0_s_axi_bid;
wire [1:0]                              c0_s_axi_bresp;
wire                                    c0_s_axi_bvalid;
wire [C0_C_S_AXI_ID_WIDTH-1:0]          c0_s_axi_arid;
wire [C0_C_S_AXI_ADDR_WIDTH-1:0]        c0_s_axi_araddr;
wire [7:0]                              c0_s_axi_arlen;
wire [2:0]                              c0_s_axi_arsize;
wire [1:0]                              c0_s_axi_arburst;
wire                                    c0_s_axi_arlock;
wire [3:0]                              c0_s_axi_arcache;
wire [2:0]                              c0_s_axi_arprot;
wire [3:0]                              c0_s_axi_arqos; // Typically 4-bit
wire [3:0]                              c0_s_axi_arregion; // Typically 4-bit
wire                                    c0_s_axi_arvalid;
wire                                    c0_s_axi_arready;
wire                                    c0_s_axi_rready;
wire [C0_C_S_AXI_ID_WIDTH-1:0]          c0_s_axi_rid;
wire [C0_C_S_AXI_DATA_WIDTH-1:0]        c0_s_axi_rdata;
wire [1:0]                              c0_s_axi_rresp;
wire                                    c0_s_axi_rlast;
wire                                    c0_s_axi_rvalid;

// MIG C0 Application Status/Control signals (wires)
wire                                    c0_app_sr_req; // App input to MIG
wire                                    c0_app_sr_active; // MIG output
wire                                    c0_app_ref_req; // App input to MIG
wire                                    c0_app_ref_ack; // MIG output
wire                                    c0_app_zq_req; // App input to MIG
wire                                    c0_app_zq_ack; // MIG output
// MIG C0 Control AXI signals (wires) - Assume connected to mig_7series_0 instance
wire [C0_C_S_AXI_CTRL_ADDR_WIDTH-1:0]   c0_s_axi_ctrl_awaddr;
wire                                    c0_s_axi_ctrl_awvalid;
wire                                    c0_s_axi_ctrl_awready;
wire [C0_C_S_AXI_CTRL_DATA_WIDTH-1:0]   c0_s_axi_ctrl_wdata;
wire                                    c0_s_axi_ctrl_wvalid;
wire                                    c0_s_axi_ctrl_wready;
wire                                    c0_s_axi_ctrl_bvalid;
wire [1:0]                              c0_s_axi_ctrl_bresp;
wire                                    c0_s_axi_ctrl_bready;
wire [C0_C_S_AXI_CTRL_ADDR_WIDTH-1:0]   c0_s_axi_ctrl_araddr;
wire                                    c0_s_axi_ctrl_arvalid;
wire                                    c0_s_axi_ctrl_arready;
wire                                    c0_s_axi_ctrl_rvalid;
wire [C0_C_S_AXI_CTRL_DATA_WIDTH-1:0]   c0_s_axi_ctrl_rdata;
wire [1:0]                              c0_s_axi_ctrl_rresp;
wire                                    c0_s_axi_ctrl_rready;
wire                                    c0_device_temp_valid; // MIG output
wire [11:0]                             c0_device_temp;      // MIG output

// MIG C1 AXI signals (wires) - Assume connected to mig_7series_1 instance
wire [C1_C_S_AXI_ID_WIDTH-1:0]          c1_s_axi_awid;
wire [C1_C_S_AXI_ADDR_WIDTH-1:0]        c1_s_axi_awaddr;
wire [7:0]                              c1_s_axi_awlen;
wire [2:0]                              c1_s_axi_awsize;
wire [1:0]                              c1_s_axi_awburst;
wire                                    c1_s_axi_awlock;
wire [3:0]                              c1_s_axi_awcache;
wire [2:0]                              c1_s_axi_awprot;
wire [3:0]                              c1_s_axi_awqos; // Typically 4-bit
wire [3:0]                              c1_s_axi_awregion; // Typically 4-bit
wire                                    c1_s_axi_awvalid;
wire                                    c1_s_axi_awready;
wire [C1_C_S_AXI_DATA_WIDTH-1:0]        c1_s_axi_wdata;
wire [(C1_C_S_AXI_DATA_WIDTH/8)-1:0]    c1_s_axi_wstrb;
wire                                    c1_s_axi_wlast;
wire                                    c1_s_axi_wvalid;
wire                                    c1_s_axi_wready;
wire                                    c1_s_axi_bready;
wire [C1_C_S_AXI_ID_WIDTH-1:0]          c1_s_axi_bid;
wire [1:0]                              c1_s_axi_bresp;
wire                                    c1_s_axi_bvalid;
wire [C1_C_S_AXI_ID_WIDTH-1:0]          c1_s_axi_arid;
wire [C1_C_S_AXI_ADDR_WIDTH-1:0]        c1_s_axi_araddr;
wire [7:0]                              c1_s_axi_arlen;
wire [2:0]                              c1_s_axi_arsize;
wire [1:0]                              c1_s_axi_arburst;
wire                                    c1_s_axi_arlock;
wire [3:0]                              c1_s_axi_arcache;
wire [2:0]                              c1_s_axi_arprot;
wire [3:0]                              c1_s_axi_arqos; // Typically 4-bit
wire [3:0