module clk_reset_corrected_clk (
    // Original Ports
    clk_in,
    reset_inout_n,
    sdram_clk, // Now muxed output
    sdram_fb,
    clk,       // Now muxed output
    clk_ok,
    reset,
    // DFT Ports
    test_mode, // Input to select test mode
    test_clk   // Input test clock (often connected to clk_in)
);

    input clk_in;
    inout reset_inout_n;
    output sdram_clk;
    input sdram_fb;
    output clk;
    output clk_ok;
    output reset;
    input test_mode; // DFT control signal
    input test_clk;  // DFT clock signal

    // Internal wires
    wire clk_in_buf;
    wire int_clk_from_dcm;
    wire func_clk; // Functional clock before DFT mux
    wire int_locked;
    wire ext_rst_n;
    wire ext_fb;
    wire sdram_clk_from_dcm; // Functional sdram clock before DFT mux
    wire ext_locked;
    reg reset_p_n;
    reg reset_s_n;
    reg [23:0] reset_counter;
    wire reset_counting;

    // Input Buffer for main clock
    IBUFG clk_in_buffer (
        .I(clk_in),
        .O(clk_in_buf)
    );

    // Internal DCM
    // Note: In real DFT flows, DCM/PLLs might be bypassed entirely in test mode.
    // This implementation assumes DCMs operate but clocks are muxed downstream.
    DCM int_dcm (
        .CLKIN(clk_in_buf),
        .CLKFB(func_clk), // Feedback functional clock
        .RST(1'b0),       // Simplified reset for this example
        .CLK0(int_clk_from_dcm),
        .LOCKED(int_locked)
    );

    // Buffer for internal clock
    BUFG int_clk_buffer (
        .I(int_clk_from_dcm),
        .O(func_clk) // Output functional clock
    );

    // SRL16 for external DCM reset generation
    // This logic is clocked by clk_in_buf, which is DFT friendly.
    SRL16 ext_dll_rst_gen (
        .CLK(clk_in_buf),
        .D(int_locked),
        .Q(ext_rst_n),
        .A0(1'b1),
        .A1(1'b1),
        .A2(1'b1),
        .A3(1'b1)
    );
    defparam ext_dll_rst_gen.INIT = 16'h0000;

    // Input buffer for feedback clock
    IBUFG ext_fb_buffer (
        .I(sdram_fb),
        .O(ext_fb)
    );

    // External DCM
    DCM ext_dcm (
        .CLKIN(clk_in_buf),
        .CLKFB(ext_fb),
        .RST(~ext_rst_n), // Use generated reset
        .CLK0(sdram_clk_from_dcm), // Output functional sdram clock
        .LOCKED(ext_locked)
    );

    // DFT Clock Muxing
    // Selects test_clk in test_mode, otherwise the functional clock generated by the DCMs.
    // This ensures downstream flops can be clocked by a primary-input-derived test clock.
    assign clk = test_mode ? test_clk : func_clk;
    assign sdram_clk = test_mode ? test_clk : sdram_clk_from_dcm;

    // Clock OK status logic
    // In test mode, lock signals might be forced/ignored by test procedures.
    assign clk_ok = int_locked & ext_locked;

    // Reset Generation Logic
    // Clocked by clk_in_buf (derived from primary input clk_in), so these FFs are scannable.
    assign reset_counting = (reset_counter == 24'hFFFFFF) ? 1'b0 : 1'b1;
    assign reset_inout_n = (reset_counter[23] == 0) ? 1'b0 : 1'bz; // Drive low during first half of count

    always @(posedge clk_in_buf) begin
        reset_p_n <= reset_inout_n;
        reset_s_n <= reset_p_n;
        if (reset_counting == 1'b1) begin // Count if reset_counting is asserted
            reset_counter <= reset_counter + 1;
        end else begin // If not counting (counter reached max or external reset)
            // Check for external reset (reset_s_n low) or loss of clock lock to restart counter
            if (~reset_s_n || ~clk_ok) begin
                reset_counter <= 24'h000000;
            end
            // else: Hold counter value if max reached and no reset condition
        end
    end

    // Final reset output signal
    // Reset is active (high) while the counter is running.
    assign reset = reset_counting;

endmodule