`default_nettype none
module plle2_test
(
input  wire         CLK,
input  wire         RST,
input  wire         I_CLKINSEL,
input  wire         test_mode, // DFT input: Select test mode
input  wire         test_clk,  // DFT input: Clock for test mode
output wire         O_LOCKED,
output wire [5:0]   O_CNT
);

// Internal clock generation (clk50 flop is scannable as clocked by CLK)
wire clk100;
reg  clk50;
assign clk100 = CLK;
always @(posedge clk100) begin
    clk50 <= !clk50;
end

wire clk_fb_o;
wire clk_fb_i;
wire [5:0] clk; // Clocks generated by PLL

// PLL instance - treated as black box for DFT scan insertion on downstream logic
PLLE2_ADV #
(
.BANDWIDTH          ("HIGH"),
.COMPENSATION       ("BUF_IN"),
.CLKIN1_PERIOD      (20.0),
.CLKIN2_PERIOD      (10.0),
.CLKFBOUT_MULT      (16),
.CLKFBOUT_PHASE     (0.0),
.CLKOUT0_DIVIDE     (16),
.CLKOUT0_DUTY_CYCLE (0.53125),
.CLKOUT0_PHASE      (45.0),
.CLKOUT1_DIVIDE     (32),
.CLKOUT1_DUTY_CYCLE (0.5),
.CLKOUT1_PHASE      (90.0),
.CLKOUT2_DIVIDE     (48),
.CLKOUT2_DUTY_CYCLE (0.5),
.CLKOUT2_PHASE      (135.0),
.CLKOUT3_DIVIDE     (64),
.CLKOUT3_DUTY_CYCLE (0.5),
.CLKOUT3_PHASE      (-45.0),
.CLKOUT4_DIVIDE     (80),
.CLKOUT4_DUTY_CYCLE (0.5),
.CLKOUT4_PHASE      (-90.0),
.CLKOUT5_DIVIDE     (96),
.CLKOUT5_DUTY_CYCLE (0.5),
.CLKOUT5_PHASE      (-135.0),
.STARTUP_WAIT       ("FALSE")
)
pll
(
.CLKIN1     (clk50),
.CLKIN2     (clk100),
.CLKINSEL   (I_CLKINSEL),
.RST        (RST), // PLL reset tied to primary reset
.LOCKED     (O_LOCKED),
.CLKFBIN    (clk_fb_i),
.CLKFBOUT   (clk_fb_o),
.CLKOUT0    (clk[0]),
.CLKOUT1    (clk[1]),
.CLKOUT2    (clk[2]),
.CLKOUT3    (clk[3]),
.CLKOUT4    (clk[4]),
.CLKOUT5    (clk[5])
);

BUFG clk_fb_buf (.I(clk_fb_o), .O(clk_fb_i));

// Functional reset depends on primary reset and PLL lock status
wire func_rst = RST || !O_LOCKED;

genvar i;
generate for (i=0; i<6; i=i+1) begin : counter_gen
  wire muxed_clk;
  wire muxed_rst;

  // Clock MUX: Select test_clk in test_mode, functional clk[i] otherwise
  // This allows the counter flops to be clocked by a primary-derived test clock during scan
  assign muxed_clk = test_mode ? test_clk : clk[i];

  // Reset MUX: Select primary RST in test_mode, functional reset otherwise
  // Ensures predictable reset behavior during test mode
  assign muxed_rst = test_mode ? RST : func_rst;

  reg [23:0] counter;

  // Counter logic using multiplexed clock and reset
  always @(posedge muxed_clk or posedge muxed_rst) begin
      if (muxed_rst) begin
          counter <= 24'b0;
      end else begin
          counter <= counter + 1;
      end
  end

  // Output assignment from counter MSB part
  assign O_CNT[i] = counter[21];

end endgenerate

endmodule
`default_nettype wire