`timescale 1ns/100ps
module axi_ad9122_if (
  dac_clk_in_p,
  dac_clk_in_n,
  dac_clk_out_p,
  dac_clk_out_n,
  dac_frame_out_p,
  dac_frame_out_n,
  dac_data_out_p,
  dac_data_out_n,
  dac_rst, // Keep original reset for serdes blocks if needed, but use up_rstn for control logic
  dac_clk,
  dac_div_clk,
  dac_status,
  dac_frame_i0,
  dac_data_i0,
  dac_frame_i1,
  dac_data_i1,
  dac_frame_i2,
  dac_data_i2,
  dac_frame_i3,
  dac_data_i3,
  dac_frame_q0,
  dac_data_q0,
  dac_frame_q1,
  dac_data_q1,
  dac_frame_q2,
  dac_data_q2,
  dac_frame_q3,
  dac_data_q3,
  mmcm_rst,
  up_clk,
  up_rstn,
  up_drp_sel,
  up_drp_wr,
  up_drp_addr,
  up_drp_wdata,
  up_drp_rdata,
  up_drp_ready,
  up_drp_locked);

  parameter   PCORE_DEVICE_TYPE = 0;
  parameter   PCORE_SERDES_DDR_N = 1;
  parameter   PCORE_MMCM_BUFIO_N = 1;
  parameter   PCORE_IODELAY_GROUP = "dac_if_delay_group";

  input           dac_clk_in_p;
  input           dac_clk_in_n;
  output          dac_clk_out_p;
  output          dac_clk_out_n;
  output          dac_frame_out_p;
  output          dac_frame_out_n;
  output  [15:0]  dac_data_out_p;
  output  [15:0]  dac_data_out_n;
  input           dac_rst;
  output          dac_clk;
  output          dac_div_clk;
  output          dac_status;
  input           dac_frame_i0;
  input   [15:0]  dac_data_i0;
  input           dac_frame_i1;
  input   [15:0]  dac_data_i1;
  input           dac_frame_i2;
  input   [15:0]  dac_data_i2;
  input           dac_frame_i3;
  input   [15:0]  dac_data_i3;
  input           dac_frame_q0;
  input   [15:0]  dac_data_q0;
  input           dac_frame_q1;
  input   [15:0]  dac_data_q1;
  input           dac_frame_q2;
  input   [15:0]  dac_data_q2;
  input           dac_frame_q3;
  input   [15:0]  dac_data_q3;

  input           mmcm_rst;
  input           up_clk;       // Primary clock input
  input           up_rstn;      // Primary reset input (active low)
  input           up_drp_sel;
  input           up_drp_wr;
  input   [11:0]  up_drp_addr;
  input   [15:0]  up_drp_wdata;
  output  [15:0]  up_drp_rdata;
  output          up_drp_ready;
  output          up_drp_locked; // MMCM lock status

  // Internal signals
  wire            dac_clk_int;     // Internal clock from MMCM
  wire            dac_div_clk_int; // Internal divided clock from MMCM
  wire            up_drp_locked_int; // Internal MMCM lock status

  reg             dac_status_m1 = 1'b0;
  reg             dac_status_reg = 1'b0;

  assign dac_clk = dac_clk_int;
  assign dac_div_clk = dac_div_clk_int;
  assign dac_status = dac_status_reg;
  assign up_drp_locked = up_drp_locked_int; // Connect internal signal to output

  // Modified logic: Use primary input clock 'up_clk' and reset 'up_rstn'
  // This ensures the flip-flops are controllable and observable for scan testing.
  always @(posedge up_clk or negedge up_rstn) begin
    if (!up_rstn) begin // Use active-low reset synchronous to up_clk
      dac_status_m1 <= 1'b0;
      dac_status_reg <= 1'b0;
    end else begin
      // Use the lock signal generated by the MMCM, but register it with up_clk
      dac_status_m1 <= up_drp_locked_int;
      dac_status_reg <= dac_status_m1;
    end
  end

  // Instantiate SERDES output blocks - these might still need DFT attention
  // depending on how dac_clk and dac_div_clk are handled (e.g., clock muxing for test)
  ad_serdes_out #(
    .DEVICE_TYPE (PCORE_DEVICE_TYPE),
    .SERDES(PCORE_SERDES_DDR_N),
    .DATA_WIDTH(16))
  i_serdes_out_data (
    .rst (dac_rst), // This reset might need review for DFT if async or from derived clock domain
    .clk (dac_clk_int),
    .div_clk (dac_div_clk_int),
    .data_s0 (dac_data_i0),
    .data_s1 (dac_data_q0),
    .data_s2 (dac_data_i1),
    .data_s3 (dac_data_q1),
    .data_s4 (dac_data_i2),
    .data_s5 (dac_data_q2),
    .data_s6 (dac_data_i3),
    .data_s7 (dac_data_q3),
    .data_out_p (dac_data_out_p),
    .data_out_n (dac_data_out_n));

  ad_serdes_out #(
    .DEVICE_TYPE (PCORE_DEVICE_TYPE),
    .SERDES(PCORE_SERDES_DDR_N),
    .DATA_WIDTH(1))
  i_serdes_out_frame (
    .rst (dac_rst),
    .clk (dac_clk_int),
    .div_clk (dac_div_clk_int),
    .data_s0 (dac_frame_i0),
    .data_s1 (dac_frame_q0),
    .data_s2 (dac_frame_i1),
    .data_s3 (dac_frame_q1),
    .data_s4 (dac_frame_i2),
    .data_s5 (dac_frame_q2),
    .data_s6 (dac_frame_i3),
    .data_s7 (dac_frame_q3),
    .data_out_p (dac_frame_out_p),
    .data_out_n (dac_frame_out_n));

  ad_serdes_out #(
    .DEVICE_TYPE (PCORE_DEVICE_TYPE),
    .SERDES(PCORE_SERDES_DDR_N),
    .DATA_WIDTH(1))
  i_serdes_out_clk (
    .rst (dac_rst),
    .clk (dac_clk_int),
    .div_clk (dac_div_clk_int),
    .data_s0 (1'b1),
    .data_s1 (1'b0),
    .data_s2 (1'b1),
    .data_s3 (1'b0),
    .data_s4 (1'b1),
    .data_s5 (1'b0),
    .data_s6 (1'b1),
    .data_s7 (1'b0),
    .data_out_p (dac_clk_out_p),
    .data_out_n (dac_clk_out_n));

  // Instantiate clock generation block
  // The outputs dac_clk_int and dac_div_clk_int are internally generated clocks.
  // For DFT, these clocks often need to be bypassed or controlled by a test clock.
  // The flip-flops clocked by these signals (inside ad_serdes_out) are problematic
  // unless the ad_serdes_clk module and ad_serdes_out modules have DFT logic (e.g., clock muxing).
  ad_serdes_clk #(
    .SERDES (PCORE_SERDES_DDR_N),
    .MMCM (PCORE_MMCM_BUFIO_N),
    .MMCM_DEVICE_TYPE (PCORE_DEVICE_TYPE),
    .MMCM_CLKIN_PERIOD (1.667),
    .MMCM_VCO_DIV (6),
    .MMCM_VCO_MUL (12),
    .MMCM_CLK0_DIV (2),
    .MMCM_CLK1_DIV (8))
  i_serdes_clk (
    .mmcm_rst (mmcm_rst),
    .clk_in_p (dac_clk_in_p),
    .clk_in_n (dac_clk_in_n),
    .clk (dac_clk_int),         // Output: internally generated clock
    .div_clk (dac_div_clk_int), // Output: internally generated clock
    .up_clk (up_clk),           // Input: primary clock (used for DRP interface)
    .up_rstn (up_rstn),         // Input: primary reset (used for DRP interface)
    .up_drp_sel (up_drp_sel),
    .up_drp_wr (up_drp_wr),
    .up_drp_addr (up_drp_addr),
    .up_drp_wdata (up_drp_wdata),
    .up_drp_rdata (up_drp_rdata),
    .up_drp_ready (up_drp_ready),
    .up_drp_locked (up_drp_locked_int)); // Output: MMCM lock status

endmodule