// 1_corrected_clk.v
module MIG_4Port	#(
	parameter C_DBUS_WIDTH           = 64,
   parameter BANK_WIDTH            	= 3,
   parameter CK_WIDTH              	= 2,
   parameter CS_WIDTH              	= 2,
   parameter nCS_PER_RANK          	= 1,
   parameter CKE_WIDTH             	= 2,
	parameter DM_WIDTH              	= 8,
   parameter DQ_WIDTH              	= 64,
	parameter DQS_WIDTH             	= 8,
   parameter ODT_WIDTH             	= 2,
   parameter ROW_WIDTH             	= 15,
	parameter ADDR_WIDTH            	= 29,
	parameter PAYLOAD_WIDTH         	= 64,
	parameter nCK_PER_CLK				= 2,
	parameter RANKS                 	= 2
)
(
	input 	[31:0]  						WR1_DATA,
	input										WR1,
	input		[ADDR_WIDTH-1:0]			WR1_ADDR,
	input		[ADDR_WIDTH-1:0]			WR1_MAX_ADDR,
	input		[31:0]						WR1_LENGTH,
	input										WR1_LOAD,
	input										WR1_CLK, // Primary Clock Input
	output									WR1_FULL,
	output	[31:0]						WR1_USE,
	output									WR1_EMPTY,
	input   	[31:0]      				WR2_DATA,
	input										WR2,
	input		[ADDR_WIDTH-1:0]			WR2_ADDR,
	input		[ADDR_WIDTH-1:0]			WR2_MAX_ADDR,
	input		[31:0]						WR2_LENGTH,
	input										WR2_LOAD,
	input										WR2_CLK, // Primary Clock Input
	output									WR2_FULL,
	output	[31:0]						WR2_USE,
	output									WR2_EMPTY,
	output  	[C_DBUS_WIDTH-1:0]      RD1_DATA,
	input										RD1,
	input		[ADDR_WIDTH-1:0]			RD1_ADDR,
	input		[ADDR_WIDTH-1:0]			RD1_MAX_ADDR,
	input		[31:0]						RD1_LENGTH,
	input										RD1_LOAD,
	input										RD1_CLK, // Primary Clock Input
	output									RD1_EMPTY,
	output	[31:0]						RD1_USE,
	input										RD1_DMA,
	output									RD1_FULL,
	output  	[C_DBUS_WIDTH-1:0]      RD2_DATA,
	input										RD2,
	input		[ADDR_WIDTH-1:0]			RD2_ADDR,
	input		[ADDR_WIDTH-1:0]			RD2_MAX_ADDR,
	input		[31:0]						RD2_LENGTH,
	input										RD2_LOAD,
	input										RD2_CLK, // Primary Clock Input
	output									RD2_EMPTY,
	output	[31:0]						RD2_USE,
	input										RD2_DMA,
	output									RD2_FULL,
	output									WR1_RDEN,WR2_RDEN,RD1_WREN,RD2_WREN,
	output	reg	[1:0]					WR_MASK,
	output	reg	[1:0]					RD_MASK,
	output	reg							mWR_DONE,
	output	reg							mRD_DONE,
	output	reg							mWR,
	output	reg							mRD,
	input		[C_DBUS_WIDTH-1:0]		DMA_us_Length,
	input		[31:0]						CH0_DMA_SIZE,CH1_DMA_SIZE,
	output	reg	[ADDR_WIDTH-1:0]			mADDR,
   inout [DQ_WIDTH-1:0]                   ddr3_dq,
   inout [DQS_WIDTH-1:0]                  ddr3_dqs_n,
   inout [DQS_WIDTH-1:0]                  ddr3_dqs_p,
   output [ROW_WIDTH-1:0]                 ddr3_addr,
   output [BANK_WIDTH-1:0]                ddr3_ba,
   output                                 ddr3_ras_n,
   output                                 ddr3_cas_n,
   output                                 ddr3_we_n,
   output                                 ddr3_reset_n,
   output [CK_WIDTH-1:0]                  ddr3_ck_p,
   output [CK_WIDTH-1:0]                  ddr3_ck_n,
   output [CKE_WIDTH-1:0]                 ddr3_cke,
   output [CS_WIDTH*nCS_PER_RANK-1:0]     ddr3_cs_n,
   output [DM_WIDTH-1:0]                  ddr3_dm,
   output [ODT_WIDTH-1:0]                 ddr3_odt,
	input                                  sys_clk_i, // Primary Clock Input
	input             							sys_clk_p,
	input             							sys_clk_n,
   input                                  sys_rst_n, // Primary Reset Input (Active Low)
	input												eb_rst,    // External Reset Input
	input												pcie_clk,  // Primary Clock Input
	output	[31:0]								ch0_ddr3_use,ch1_ddr3_use,
	output	reg									ch0_ddr3_full,ch1_ddr3_full,
	output	reg									ch0_valid,ch1_valid,
	output											init_calib_complete,
	output											ui_clk, // Clock generated by ddr3_ip
	output											ui_clk_sync_rst, // Reset generated by ddr3_ip
	output											sys_clk_o
	);

	localparam		BURST_BYTE 				= 8*1024;
	localparam		BURST_UIDATA_LEN		= BURST_BYTE>>5;
	localparam	 	BURST_ADDR_LEN			= BURST_UIDATA_LEN >> 1;

	// DFT Fix: Generate synchronous reset from primary reset sys_rst_n and primary clock sys_clk_i
	reg rst_sync_r1, rst_sync_r2;
	wire sys_clk_rst; // Active high synchronous reset for logic clocked by sys_clk_i

	always @(posedge sys_clk_i or negedge sys_rst_n) begin
		if (!sys_rst_n) begin
			rst_sync_r1 <= 1'b1;
			rst_sync_r2 <= 1'b1;
		end else begin
			rst_sync_r1 <= 1'b0;
			rst_sync_r2 <= rst_sync_r1;
		end
	end
	assign sys_clk_rst = rst_sync_r2; // Use this reset for logic clocked by sys_clk_i

	// Original complex reset - kept for reference or potential use where ui_clk domain reset is needed
	// wire	rst = (ui_clk_sync_rst | eb_rst) | (~init_calib_complete);


	wire												app_rdy;
	reg												app_en;
	reg	[2:0]										app_cmd;
	wire	[ADDR_WIDTH-1:0]						app_addr;
	wire												app_wdf_rdy;
	reg												app_wdf_wren;
	reg												app_wdf_end;
	wire	[(4*PAYLOAD_WIDTH)-1:0]				app_wdf_data;
	wire	[(4*PAYLOAD_WIDTH)/8-1:0]			app_wdf_mask=32'd0;
	wire												app_rd_data_valid;
	wire	[(4*PAYLOAD_WIDTH)-1:0]				app_rd_data;
	reg	[31:0]							mDATA_LENGTH;
	reg	[31:0]						mADDR_LENGTH;
	reg	[ADDR_WIDTH-1:0]			rWR1_ADDR;
	reg	[ADDR_WIDTH-1:0]			rWR1_MAX_ADDR;
	reg	[31:0]						rWR1_ADDR_LENGTH;
	reg	[31:0]						rWR1_DATA_LENGTH;
	reg	[ADDR_WIDTH-1:0]			rWR2_ADDR;
	reg	[ADDR_WIDTH-1:0]			rWR2_MAX_ADDR;
	reg	[31:0]						rWR2_ADDR_LENGTH;
	reg	[31:0]						rWR2_DATA_LENGTH;
	reg	[ADDR_WIDTH-1:0]			rRD1_ADDR;
	reg	[ADDR_WIDTH-1:0]			rRD1_MAX_ADDR;
	reg	[31:0]						rRD1_ADDR_LENGTH;
	reg	[31:0]						rRD1_DATA_LENGTH;
	reg	[ADDR_WIDTH-1:0]			rRD2_ADDR;
	reg	[ADDR_WIDTH-1:0]			rRD2_MAX_ADDR;
	reg	[31:0]						rRD2_ADDR_LENGTH;
	reg	[31:0]						rRD2_DATA_LENGTH;
	wire  [(4*PAYLOAD_WIDTH)-1:0]   	mDATAIN1;
	wire  [(4*PAYLOAD_WIDTH)-1:0]   	mDATAIN2;
	wire	[9:0]							write_side_fifo_rusedw1;
	wire	[9:0]							read_side_fifo_wusedw1;
	wire	[9:0]							write_side_fifo_rusedw2;
	wire	[9:0]							read_side_fifo_wusedw2;


  ddr3_ip #(
   .BANK_WIDTH            	(BANK_WIDTH    ),
   .CK_WIDTH              	(CK_WIDTH      ),
   .CS_WIDTH              	(CS_WIDTH      ),
   .nCS_PER_RANK          	(nCS_PER_RANK  ),
   .CKE_WIDTH             	(CKE_WIDTH     ),
	.DM_WIDTH              	(DM_WIDTH      ),
   .DQ_WIDTH              	(DQ_WIDTH      ),
	.DQS_WIDTH             	(DQS_WIDTH     ),
   .ODT_WIDTH             	(ODT_WIDTH     ),
   .ROW_WIDTH             	(ROW_WIDTH     ),
	.ADDR_WIDTH            	(ADDR_WIDTH    ),
	.PAYLOAD_WIDTH         	(PAYLOAD_WIDTH ),
	.nCK_PER_CLK				(nCK_PER_CLK	),
	.RANKS						(RANKS			)
)	u_ddr3_ip
      (
       .ddr3_addr                      (ddr3_addr),
       .ddr3_ba                        (ddr3_ba),
       .ddr3_cas_n                     (ddr3_cas_n),
       .ddr3_ck_n                      (ddr3_ck_n),
       .ddr3_ck_p                      (ddr3_ck_p),
       .ddr3_cke                       (ddr3_cke),
       .ddr3_ras_n                     (ddr3_ras_n),
       .ddr3_reset_n                   (ddr3_reset_n),
       .ddr3_we_n                      (ddr3_we_n),
       .ddr3_dq                        (ddr3_dq),
       .ddr3_dqs_n                     (ddr3_dqs_n),
       .ddr3_dqs_p                     (ddr3_dqs_p),
       .init_calib_complete            (init_calib_complete),
       .ddr3_cs_n                      (ddr3_cs_n),
       .ddr3_dm                        (ddr3_dm),
       .ddr3_odt                       (ddr3_odt),
       .app_addr                       (app_addr), // Driven by logic now clocked by sys_clk_i (CDC needed)
       .app_cmd                        (app_cmd), // Driven by logic now clocked by sys_clk_i (CDC needed)
       .app_en                         (app_en), // Driven by logic now clocked by sys_clk_i (CDC needed)
       .app_wdf_data                   (app_wdf_data), // Driven by logic now clocked by sys_clk_i (CDC needed)
       .app_wdf_end                    (app_wdf_end), // Driven by logic now clocked by sys_clk_i (CDC needed)
       .app_wdf_wren                   (app_wdf_wren), // Driven by logic now clocked by sys_clk_i (CDC needed)
       .app_rd_data                    (app_rd_data), // Output in ui_clk domain (CDC needed)
       .app_rd_data_end                (app_rd_data_end), // Output in ui_clk domain (CDC needed)
       .app_rd_data_valid              (app_rd_data_valid), // Output in ui_clk domain (CDC needed)
       .app_rdy                        (app_rdy), // Output in ui_clk domain (CDC needed)
       .app_wdf_rdy                    (app_wdf_rdy), // Output in ui_clk domain (CDC needed)
       .app_sr_req                     (1'b0),
       .app_sr_active                  (app_sr_active),
       .app_ref_req                    (1'b0),
       .app_ref_ack                    (app_ref_ack),
       .app_zq_req                     (1'b0),
       .app_zq_ack                     (app_zq_ack),
       .ui_clk                         (ui_clk), // Generated clock output
       .ui_clk_sync_rst                (ui_clk_sync_rst), // Generated reset output
       .app_wdf_mask                   (app_wdf_mask),
       .sys_clk_i                      (sys_clk_i),
		 .sys_clk_p								(sys_clk_p),
		 .sys_clk_n								(sys_clk_n),
       .sys_rst                        (sys_rst_n), // Primary reset input to IP
		 .sys_clk_o								(sys_clk_o)
       );


// DFT Fix: Ensure FIFOs use synchronous reset and primary clocks where appropriate.
// Note: Changing rd_clk/wr_clk requires careful CDC analysis for functional correctness.
// This change primarily addresses the DFT requirement of using primary/controllable clocks.

wr_fifo32to256 write_fifo1 (
  .rst					(sys_clk_rst), // Use synchronous reset
  .wr_clk				(WR1_CLK),     // Primary input clock
  .rd_clk				(sys_clk_i),   // DFT Fix: Use primary clock sys_clk_i instead of ui_clk
  .din					(WR1_DATA),
  .wr_en					(WR1),
  .rd_en					(WR1_RDEN), // Driven by logic clocked by sys_clk_i
  .dout					(mDATAIN1),    // Output used by logic clocked by sys_clk_i
  .full					(WR1_FULL),
  .empty					(WR1_EMPTY),
  .rd_data_count		(write_side_fifo_rusedw1), // Output used by logic clocked by sys_clk_i
  .wr_data_count		(WR1_USE)
);
// WR1_RDEN logic depends on app_wdf_rdy (from ui_clk domain) and WR_MASK (from sys_clk_i domain) - Needs CDC
assign	WR1_RDEN = 	app_wdf_wren & app_wdf_rdy & WR_MASK[0]; // Needs CDC for app_wdf_rdy and app_wdf_wren

wr_fifo32to256 write_fifo2 (
  .rst					(sys_clk_rst), // Use synchronous reset
  .wr_clk				(WR2_CLK),     // Primary input clock
  .rd_clk				(sys_clk_i),   // DFT Fix: Use primary clock sys_clk_i instead of ui_clk
  .din					(WR2_DATA),
  .wr_en					(WR2),
  .rd_en					(WR2_RDEN), // Driven by logic clocked by sys_clk_i
  .dout					(mDATAIN2),    // Output used by logic clocked by sys_clk_i
  .full					(WR2_FULL),
  .empty					(WR2_EMPTY),
  .rd_data_count		(write_side_fifo_rusedw2), // Output used by logic clocked by sys_clk_i
  .wr_data_count		(WR2_USE)
);
// WR2_RDEN logic depends on app_wdf_rdy (from ui_clk domain) and WR_MASK (from sys_clk_i domain) - Needs CDC
assign	WR2_RDEN = 	app_wdf_wren & app_wdf_rdy & WR_MASK[1]; // Needs CDC for app_wdf_rdy and app_wdf_wren

// app_wdf_data selection depends on WR_MASK (sys_clk_i domain) and drives ddr3_ip (ui_clk domain) - Needs CDC
assign	app_wdf_data	=	(WR_MASK[0]) ?	mDATAIN1	: mDATAIN2	;

rd_fifo_256to64 read_fifo1 (
  .rst					(sys_clk_rst), // Use synchronous reset
  .wr_clk				(sys_clk_i),   // DFT Fix: Use primary clock sys_clk_i instead of ui_clk
  .rd_clk				(RD1_CLK),     // Primary input clock
  .din					(app_rd_data), // Input from ddr3_ip (ui_clk domain) - Needs CDC
  .wr_en					(RD1_WREN),    // Driven by logic clocked by sys_clk_i
  .rd_en					(RD1),
  .dout					(RD1_DATA),
  .full					(RD1_FULL),
  .empty					(RD1_EMPTY),
  .prog_full			(RD1_prog_full), // Output used by logic clocked by sys_clk_i
  .rd_data_count		(RD1_USE),
  .wr_data_count		(read_side_fifo_wusedw1) // Output used by logic clocked by sys_clk_i
);
// RD1_WREN depends on app_rd_data_valid (ui_clk domain) and RD_MASK (sys_clk_i domain) - Needs CDC
assign RD1_WREN = app_rd_data_valid & RD_MASK[0]; // Needs CDC for app_rd_data_valid

rd_fifo_256to64 read_fifo2 (
  .rst					(sys_clk_rst), // Use synchronous reset
  .wr_clk				(sys_clk_i),   // DFT Fix: Use primary clock sys_clk_i instead of ui_clk
  .rd_clk				(RD2_CLK),     // Primary input clock
  .din					(app_rd_data), // Input from ddr3_ip (ui_clk domain) - Needs CDC
  .wr_en					(RD2_WREN),    //