`timescale 1ps/1ps
// 1_corrected_clk.v
module clk_dll_exdes
 #(
  parameter TCQ = 100
  )
 (
  input         CLK_IN1,        // Primary clock input, also used as test clock
  input         COUNTER_RESET,
  output [3:1]  CLK_OUT,
  output [3:1]  COUNT,
  input         RESET,
  input         test_mode,      // Test mode select signal
  output        LOCKED
 );
  localparam    C_W       = 16;
  localparam    NUM_C     = 3;
  genvar        count_gen;

  // Asynchronous reset generation - Note: This might still be a DFT concern
  // depending on test strategy for asynchronous resets.
  wire          reset_int = !LOCKED || RESET || COUNTER_RESET;

  reg [NUM_C:1] rst_sync;
  reg [NUM_C:1] rst_sync_int;
  reg [NUM_C:1] rst_sync_int1;
  reg [NUM_C:1] rst_sync_int2;

  wire [NUM_C:1] clk_int;        // Clocks generated by the DLL
  wire [NUM_C:1] clk_n;          // Inverted functional clocks for ODDR
  wire [NUM_C:1] clk;            // Functional clocks (assigned from clk_int)
  wire [NUM_C:1] test_clk_muxed; // Muxed clock signal for internal FFs

  reg [C_W-1:0]  counter [NUM_C:1];

  // Instantiate the clock DLL
  clk_dll clknetwork
   (
    .clk50in            (CLK_IN1),
    .clk50              (clk_int[1]),
    .clk25              (clk_int[2]),
    .clk3p2             (clk_int[3]),
    .RESET              (RESET),
    .LOCKED             (LOCKED)
   );

  // Assign functional clocks from DLL outputs
  assign clk[1] = clk_int[1];
  assign clk[2] = clk_int[2];
  assign clk[3] = clk_int[3];

  // Generate clock multiplexers and clocked logic for counters and synchronizers
  generate for (count_gen = 1; count_gen <= NUM_C; count_gen = count_gen + 1) begin: counters_and_mux

    // Clock Mux: Selects primary clock CLK_IN1 in test_mode,
    // otherwise selects the functional clock clk[count_gen]
    assign test_clk_muxed[count_gen] = test_mode ? CLK_IN1 : clk[count_gen];

    // --- Reset Synchronizer Flip-Flops ---
    // Clocked by the muxed clock. Uses asynchronous reset 'reset_int'.
    // Note: Asynchronous reset handling is crucial for DFT.
    always @(posedge reset_int or posedge test_clk_muxed[count_gen]) begin
       if (reset_int) begin
            rst_sync[count_gen]      <= 1'b1;
            rst_sync_int[count_gen]  <= 1'b1;
            rst_sync_int1[count_gen] <= 1'b1;
            rst_sync_int2[count_gen] <= 1'b1;
       end
       else begin
            rst_sync[count_gen]      <= 1'b0;
            rst_sync_int[count_gen]  <= rst_sync[count_gen];
            rst_sync_int1[count_gen] <= rst_sync_int[count_gen];
            rst_sync_int2[count_gen] <= rst_sync_int1[count_gen];
       end
    end

    // --- Counter Flip-Flops ---
    // Clocked by the muxed clock. Uses asynchronous reset 'rst_sync_int2'.
    // Note: Asynchronous reset derived from internal logic (rst_sync_int2) is a DFT concern.
    always @(posedge test_clk_muxed[count_gen] or posedge rst_sync_int2[count_gen]) begin
      if (rst_sync_int2[count_gen]) begin
        counter[count_gen] <= #TCQ { C_W { 1'b 0 } };
      end else begin
        counter[count_gen] <= #TCQ counter[count_gen] + 1'b 1;
      end
    end

    // Assign counter output bit
    assign COUNT[count_gen] = counter[count_gen][C_W-1];

  end
  endgenerate

  // --- Output Clock Generation using ODDR2 ---
  // This part still uses the functional clocks (clk, clk_n) generated by the DLL.
  // For full DFT coverage including these outputs, the ODDR clock inputs
  // might also need to be muxed with the test clock, depending on the DFT strategy.
  genvar clk_out_pins;
  generate
    for (clk_out_pins = 1; clk_out_pins <= NUM_C; clk_out_pins = clk_out_pins + 1)
    begin: gen_outclk_oddr
      // Invert the functional clock for ODDR C1 input
      assign clk_n[clk_out_pins] = ~clk[clk_out_pins];

      // ODDR instance for generating output clocks
      ODDR2 clkout_oddr
       (
        .Q  (CLK_OUT[clk_out_pins]), // Output clock pin
        .C0 (clk[clk_out_pins]),     // Functional clock (posedge)
        .C1 (clk_n[clk_out_pins]),   // Inverted functional clock (negedge)
        .CE (1'b1),                  // Clock Enable tied high
        .D0 (1'b1),                  // Data input for posedge clock
        .D1 (1'b0),                  // Data input for negedge clock
        .R  (1'b0),                  // Reset tied low
        .S  (1'b0)                   // Set tied low
       );
    end
  endgenerate

endmodule