`timescale 1ps/1ps
module Clock48MHZ_exdes_corrected_clk
 #(
  parameter TCQ = 100
  )
 (
  input         CLK_IN1,         // Primary functional clock input
  input         COUNTER_RESET,   // Primary functional reset input
  input         test_clk,        // Primary test clock input
  input         test_mode,       // Test mode enable signal
  input         test_reset,      // Primary test reset input (active high, synchronous)
  output [4:1]  CLK_OUT,
  output [4:1]  COUNT,
  output        LOCKED           // Output from Clock48MHZ indicating lock
 );

  localparam    C_W       = 16;
  localparam    NUM_C     = 4;
  genvar        count_gen;

  // Internal signals
  wire          functional_reset = !LOCKED || COUNTER_RESET; // Functional reset condition
  wire [NUM_C:1] muxed_clk;       // Clock signal selected based on test_mode
  wire [NUM_C:1] effective_counter_reset; // Effective synchronous reset for counters

  reg [NUM_C:1] rst_sync;
  reg [NUM_C:1] rst_sync_int;
  reg [NUM_C:1] rst_sync_int1;
  reg [NUM_C:1] rst_sync_int2; // Output of reset synchronizer chain

  wire [NUM_C:1] clk_int;         // Clocks generated by Clock48MHZ module
  wire [NUM_C:1] clk;             // Intermediate clock wires (functional clocks)

  reg [C_W-1:0]  counter [NUM_C:1];

  // Instantiate the clock generator module
  Clock48MHZ clknetwork
   (
    .CLK_100            (CLK_IN1),
    .CLK_48             (clk_int[1]),
    .CLK_OUT1           (clk_int[2]),
    .CLK_OUT2           (clk_int[3]),
    .CLK_OUT4           (clk_int[4]),
    .LOCKED             (LOCKED)
   );

  // Assign functional clocks
  assign clk[1] = clk_int[1];
  assign clk[2] = clk_int[2];
  assign clk[3] = clk_int[3];
  assign clk[4] = clk_int[4];

  // Generate clock multiplexers and reset logic for each clock domain
  generate
    for (count_gen = 1; count_gen <= NUM_C; count_gen = count_gen + 1) begin: clk_mux_gen
      // Multiplex between functional clock and test clock
      assign muxed_clk[count_gen] = test_mode ? test_clk : clk[count_gen];

      // Define effective synchronous reset for the counter in this domain
      assign effective_counter_reset[count_gen] = test_mode ? test_reset : rst_sync_int2[count_gen];
    end
  endgenerate

  // Generate ODDR instances for clock outputs, clocked by muxed clock
  genvar clk_out_pins;
  generate
    for (clk_out_pins = 1; clk_out_pins <= NUM_C; clk_out_pins = clk_out_pins + 1) begin: gen_outclk_oddr
      ODDR clkout_oddr
       (
        .Q  (CLK_OUT[clk_out_pins]),
        .C  (muxed_clk[clk_out_pins]), // Use muxed clock
        .CE (1'b1),
        .D1 (1'b1),
        .D2 (1'b0),
        .R  (1'b0), // Assuming ODDR reset is not used or handled separately
        .S  (1'b0)  // Assuming ODDR set is not used or handled separately
       );
    end
  endgenerate

  // Generate reset synchronizer chains (now fully synchronous)
  generate
    for (count_gen = 1; count_gen <= NUM_C; count_gen = count_gen + 1) begin: counters_1_sync_reset
      // Synchronous reset synchronizer logic
      always @(posedge muxed_clk[count_gen]) begin
        if (test_mode && test_reset) begin // Test reset overrides functional logic
             rst_sync[count_gen]      <= #TCQ 1'b1; // Assert reset synchronously during test reset
             rst_sync_int[count_gen]  <= #TCQ 1'b1;
             rst_sync_int1[count_gen] <= #TCQ 1'b1;
             rst_sync_int2[count_gen] <= #TCQ 1'b1;
        end else begin // Functional mode or test mode without test_reset active
             // Synchronize the functional_reset signal across clock domains
             rst_sync[count_gen]      <= #TCQ functional_reset; // Sample functional reset
             rst_sync_int[count_gen]  <= #TCQ rst_sync[count_gen];
             rst_sync_int1[count_gen] <= #TCQ rst_sync_int[count_gen];
             rst_sync_int2[count_gen] <= #TCQ rst_sync_int1[count_gen]; // Final synchronized reset stage
        end
      end
    end
  endgenerate

  // Generate counters with synchronous reset
  generate
    for (count_gen = 1; count_gen <= NUM_C; count_gen = count_gen + 1) begin: counters_sync_reset
      // Counter logic with synchronous reset
      always @(posedge muxed_clk[count_gen]) begin
        // Use the effective synchronous reset for this counter
        if (effective_counter_reset[count_gen]) begin
          counter[count_gen] <= #TCQ { C_W { 1'b0 } }; // Reset counter synchronously
        end else begin
          counter[count_gen] <= #TCQ counter[count_gen] + 1'b1; // Increment counter
        end
      end
      // Assign counter output bit
      assign COUNT[count_gen] = counter[count_gen][C_W-1];
    end
  endgenerate

endmodule