`timescale 1ns / 1ps
// 1_corrected_clk.v
module AXI_DDR2_MIG(
      input         CLK,                // Primary system clock
      input			    CLK_333MHZ,         // Primary clock for DDR PHY
      input			    CLK_200MHZ,         // Primary clock for DDR Ref
      input         RST,                // Primary reset (active high)
      input           axi_awvalid,
      output          axi_awready,
      input  [32-1:0] axi_awaddr,
      input  [3-1:0]  axi_awprot,
      input           axi_wvalid,
      output          axi_wready,
      input  [32-1:0] axi_wdata,
      input  [4-1:0]  axi_wstrb,
      output          axi_bvalid,
      input           axi_bready,
      input           axi_arvalid,
      output          axi_arready,
      input  [32-1:0] axi_araddr,
      input  [3-1:0]  axi_arprot,
      output          axi_rvalid,
      input           axi_rready,
      output [32-1:0] axi_rdata,
      // DDR2 Interface
      output [12:0] ddr2_addr,
      output [2:0]  ddr2_ba,
      output        ddr2_ras_n,
      output        ddr2_cas_n,
      output        ddr2_we_n,
      output [0:0]  ddr2_ck_p,
      output [0:0]  ddr2_ck_n,
      output [0:0]  ddr2_cke,
      output [0:0]  ddr2_cs_n,
      output [1:0]  ddr2_dm,
      output [0:0]  ddr2_odt,
      inout  [15:0] ddr2_dq,
      inout  [1:0]  ddr2_dqs_p,
      inout  [1:0]  ddr2_dqs_n
    );

    wire rst_i; // Internal active-low reset
    assign rst_i = ~RST;
    wire rstn; // Active-low reset for DDR2 IP
    assign rstn = rst_i;

    // DDR2 IP Signals
    wire mem_ui_clk; // Clock generated by DDR2 IP (Problematic for DFT)
    wire mem_ui_rst; // Reset generated by DDR2 IP
    wire mem_init_calib_complete;
    wire mem_rdy;
    wire mem_wdf_rdy;
    wire [63:0] mem_rd_data;
    wire mem_rd_data_end;
    wire mem_rd_data_valid;

    // --- Synchronizers for signals from mem_ui_clk domain to CLK domain ---
    reg mem_init_calib_complete_s1, mem_init_calib_complete_clk;
    reg mem_rdy_s1, mem_rdy_clk;
    reg mem_wdf_rdy_s1, mem_wdf_rdy_clk;
    reg mem_rd_data_valid_s1, mem_rd_data_valid_clk;
    reg mem_rd_data_end_s1, mem_rd_data_end_clk;
    reg [63:0] mem_rd_data_s1, mem_rd_data_clk;

    always @(posedge CLK or negedge rst_i) begin
        if (!rst_i) begin
            mem_init_calib_complete_s1 <= 1'b0;
            mem_init_calib_complete_clk <= 1'b0;
            mem_rdy_s1 <= 1'b0;
            mem_rdy_clk <= 1'b0;
            mem_wdf_rdy_s1 <= 1'b0;
            mem_wdf_rdy_clk <= 1'b0;
            mem_rd_data_valid_s1 <= 1'b0;
            mem_rd_data_valid_clk <= 1'b0;
            mem_rd_data_end_s1 <= 1'b0;
            mem_rd_data_end_clk <= 1'b0;
            mem_rd_data_s1 <= 64'b0;
            mem_rd_data_clk <= 64'b0;
        end else begin
            mem_init_calib_complete_s1 <= mem_init_calib_complete;
            mem_init_calib_complete_clk <= mem_init_calib_complete_s1;
            mem_rdy_s1 <= mem_rdy;
            mem_rdy_clk <= mem_rdy_s1;
            mem_wdf_rdy_s1 <= mem_wdf_rdy;
            mem_wdf_rdy_clk <= mem_wdf_rdy_s1;
            mem_rd_data_valid_s1 <= mem_rd_data_valid;
            mem_rd_data_valid_clk <= mem_rd_data_valid_s1;
            mem_rd_data_end_s1 <= mem_rd_data_end;
            mem_rd_data_end_clk <= mem_rd_data_end_s1;
            mem_rd_data_s1 <= mem_rd_data;
            mem_rd_data_clk <= mem_rd_data_s1;
        end
    end

    // --- Logic operating on primary CLK domain ---
    localparam [2:0] CMD_WRITE = 3'b000;
    localparam [2:0] CMD_READ  = 3'b001;

    reg [31:0] waddr, raddr;
    reg [31:0] wdata;
	reg [3:0] wstrb;
    reg [1:0] wassert; // [0]=aw, [1]=w
    reg rassert;

    // Input AXI request registering (SINGLE_SHOT logic)
    always @(posedge CLK or negedge rst_i) // Use primary clock and reset
    begin : SINGLE_SHOT
        if (rst_i == 1'b0) begin
            waddr <= 32'b0;
            raddr <= 32'b0;
            wdata <= 32'b0;
			wstrb <= 4'b0;
            wassert <= 2'b00;
            rassert <= 1'b0;
        end else begin
            // Write Address Channel
            if (axi_bvalid && axi_bready) begin // Use axi_bvalid from this domain
                wassert[0] <= 1'b0; // Clear address assert when transaction completes
            end else if (axi_awvalid && axi_awready) begin // Use axi_awready from this domain
                waddr <= axi_awaddr;
                wassert[0] <= 1'b1;
            end // No else needed, keep wassert[0] if no new command and not completing

            // Write Data Channel
            if (axi_bvalid && axi_bready) begin // Use axi_bvalid from this domain
                wassert[1] <= 1'b0; // Clear data assert when transaction completes
            end else if (axi_wvalid && axi_wready) begin // Use axi_wready from this domain
                wdata <= axi_wdata;
                wstrb <= axi_wstrb; // Capture strobe with data
                wassert[1] <= 1'b1;
            end // No else needed, keep wassert[1] if no new data and not completing

            // Read Address Channel
            if (axi_rvalid && axi_rready) begin // Use axi_rvalid from this domain
                // Assuming one read command completes per rvalid assertion
                // More complex logic might be needed for bursts
                rassert <= 1'b0; // Clear assert when read data accepted
            end else if (axi_arvalid && axi_arready) begin // Use axi_arready from this domain
                raddr <= axi_araddr;
                rassert <= 1'b1;
            end // No else needed, keep rassert if no new command and not completing
        end
    end

    // State machine and DDR command generation (now clocked by CLK)
	parameter st0_nothing = 0, st2_CheckRdy = 2, st3_WaitRdy = 3, st4_detour = 4, st5_wready = 5, st6_rready = 6, st7_waitclean = 7;
	reg [3:0] state;
	reg is_writting; // Indicates if current operation is write or read

    // State machine outputs (registered in CLK domain)
    reg axi_bvalid_clk;
    reg axi_rvalid_clk;
    reg [31:0] axi_rdata_clk;
    reg block_clk; // Blocks new AXI requests
    reg [26:0]  mem_addr_clk;
    reg [2:0]  mem_cmd_clk;
    reg mem_en_clk;
    reg [63:0] mem_wdf_data_clk;
    reg mem_wdf_end_clk;
    reg [7:0] mem_wdf_mask_clk;
    reg mem_wdf_wren_clk;

    // Read data registering (in CLK domain)
    reg [63:0] rd_data_clk1, rd_data_clk2;

	always @ (posedge CLK or negedge rst_i) begin // Use primary clock and reset
		if (rst_i == 1'b0) begin
            // Reset state machine outputs
			axi_bvalid_clk <= 1'b0;
			axi_rvalid_clk <= 1'b0;
			axi_rdata_clk <= 32'b0;
			is_writting <= 1'b0;
			state <= st0_nothing;
			mem_wdf_wren_clk <= 1'b0;
            mem_wdf_end_clk <= 1'b0;
            mem_en_clk <= 1'b0;
			mem_cmd_clk <= 3'b0;
            mem_addr_clk <= 27'b0;
            mem_wdf_data_clk <= 64'b0;
            mem_wdf_mask_clk <= 8'b0;
			block_clk <= 1'b0; // Don't block initially
            // Reset read data registers
            rd_data_clk1 <= 64'b0;
            rd_data_clk2 <= 64'b0;
		end else begin
            // Register synchronized read data path signals
            rd_data_clk1 <= mem_rd_data_clk;
            rd_data_clk2 <= rd_data_clk1;

            // Default assignments (hold values)
            axi_bvalid_clk <= axi_bvalid_clk;
            axi_rvalid_clk <= axi_rvalid_clk;
            axi_rdata_clk <= axi_rdata_clk;
            block_clk <= block_clk;
            mem_wdf_wren_clk <= 1'b0; // Default off
            mem_wdf_end_clk <= 1'b0;  // Default off
            mem_en_clk <= 1'b0;     // Default off

			case (state)
				st0_nothing: begin
                    block_clk <= 1'b0; // Not blocking in idle state
                    axi_bvalid_clk <= 1'b0; // Ensure flags are low
                    axi_rvalid_clk <= 1'b0;
					if(mem_init_calib_complete_clk == 1'b1) begin // Use synchronized signal
						if(mem_rdy_clk == 1'b1) begin // Use synchronized signal
							if(mem_wdf_rdy_clk == 1'b1) begin // Use synchronized signal
								if(&wassert == 1'b1) begin // Use wassert directly from CLK domain (&wassert checks both addr and data valid)
									state <= st2_CheckRdy;
									mem_cmd_clk <= CMD_WRITE;
									mem_wdf_wren_clk <= 1'b1;
									mem_wdf_end_clk <= 1'b1;
									mem_en_clk <= 1'b1;
									mem_addr_clk <= {waddr[29:3], 3'b000}; // Use waddr directly
									mem_wdf_data_clk <= {wdata, wdata}; // Use wdata directly (assuming 64-bit DDR width)
									// Calculate mask based on wstrb and low address bit
									mem_wdf_mask_clk <= {~{wstrb & {4{waddr[2]}}}, ~{wstrb & {4{~waddr[2]}}}}; // Use wstrb, waddr directly
									is_writting <= 1'b1;
                                    block_clk <= 1'b1; // Block new requests
								end else if(rassert == 1'b1) begin // Use rassert directly from CLK domain
									state <= st2_CheckRdy;
									mem_cmd_clk <= CMD_READ;
									mem_en_clk <= 1'b1;
									mem_addr_clk <= {raddr[29:3], 3'b000}; // Use raddr directly
									is_writting <= 1'b0;