`timescale 1ns / 1ps
module AXI_DDR3_MIG_corrected ( // Renamed module slightly for clarity, original name preserved in comments if needed
      // Primary Clocks and Reset
      input         CLK,                // Primary system clock
      input			    CLK_333MHZ,         // DDR3 System Clock Input
      input			    CLK_200MHZ,         // DDR3 Reference Clock Input
      input         RST,                // Primary asynchronous reset (active high)
      input         TEST_MODE,          // DFT Test Mode enable
      input         TEST_CLK,           // DFT Test Clock input

      // AXI Write Address Channel
      input           axi_awvalid,
      output          axi_awready,
      input  [32-1:0] axi_awaddr,
      input  [3-1:0]  axi_awprot,

      // AXI Write Data Channel
      input           axi_wvalid,
      output          axi_wready,
      input  [32-1:0] axi_wdata,
      input  [4-1:0]  axi_wstrb,

      // AXI Write Response Channel
      output          axi_bvalid,
      input           axi_bready,

      // AXI Read Address Channel
      input           axi_arvalid,
      output          axi_arready,
      input  [32-1:0] axi_araddr,
      input  [3-1:0]  axi_arprot,

      // AXI Read Data Channel
      output          axi_rvalid,
      input           axi_rready,
      output [32-1:0] axi_rdata,

      // DDR3 Interface
      output [12:0] ddr3_addr,
      output [2:0]  ddr3_ba,
      output        ddr3_ras_n,
      output        ddr3_cas_n,
      output        ddr3_we_n,
      output [0:0]  ddr3_ck_p,
      output [0:0]  ddr3_ck_n,
      output [0:0]  ddr3_cke,
      output [0:0]  ddr3_cs_n,
      output [1:0]  ddr3_dm,
      output [0:0]  ddr3_odt,
      inout  [15:0] ddr3_dq,
      inout  [1:0]  ddr3_dqs_p,
      inout  [1:0]  ddr3_dqs_n
    );

    // Internal Signals
    wire rst_i;             // Inverted primary reset (active low)
    assign rst_i = ~RST;

    localparam [2:0] CMD_WRITE = 3'b000;
    localparam [2:0] CMD_READ  = 3'b001;

    // DDR3 MIG Interface Signals
    wire mem_ui_clk;            // Clock generated by MIG core
    wire mem_ui_rst;            // Reset generated by MIG core (active high)
    wire mem_init_calib_complete; // Calibration status from MIG
    wire mem_rdy;               // MIG ready for new command
    wire mem_wdf_rdy;           // MIG write data FIFO ready
    wire [63:0] mem_rd_data;       // MIG read data output
    wire mem_rd_data_end;       // MIG read data end flag
    wire mem_rd_data_valid;     // MIG read data valid flag

    // DFT Clock and Reset Selection
    wire effective_mem_clk;     // Clock for MIG interface logic (Testable)
    wire effective_mem_rst_n;   // Reset for MIG interface logic (Testable, active low)
    wire mig_rst_def;           // Original MIG domain reset (active low)

    assign mig_rst_def = ~(rst_i | mem_ui_rst); // Active low reset for MIG domain logic
    assign effective_mem_clk = TEST_MODE ? TEST_CLK : mem_ui_clk;
    assign effective_mem_rst_n = TEST_MODE ? rst_i : mig_rst_def; // Use primary reset in test mode

    // AXI Interface Registers (CLK domain)
    reg [31:0] waddr, raddr;
    reg [31:0] wdata;
	reg [3:0] wstrb;
    reg [1:0] wassert;
    reg rassert;

    // State Machine and MIG Interface Registers (effective_mem_clk domain)
    reg [26:0]  mem_addr;
    reg [2:0]  mem_cmd;
    reg mem_en;
    reg [63:0] mem_wdf_data;
    reg mem_wdf_end;
    reg [7:0] mem_wdf_mask;
    reg mem_wdf_wren;
	reg rd_vld;
    reg rd_end;
    reg [63:0] rd_data_1, rd_data_2;
	reg block_o; // Internal block signal (effective_mem_clk domain)
    parameter [3:0] st0_nothing = 4'd0, st2_CheckRdy = 4'd2, st3_WaitRdy = 4'd3, st4_detour = 4'd4, st5_wready = 4'd5, st6_rready = 4'd6, st7_waitclean = 4'd7;
	reg [3:0] state;
	reg is_writting;
	reg axi_bvalid_o; // Internal BVALID signal (effective_mem_clk domain)
	reg axi_rvalid_o; // Internal RVALID signal (effective_mem_clk domain)
	reg [31:0] axi_rdata_o; // Internal RDATA signal (effective_mem_clk domain)

    // AXI Ready Logic (Combinational based on block signal from effective_mem_clk domain)
    wire block; // block_o synchronized to CLK domain
    assign axi_awready = ~block;
    assign axi_arready = ~block;
    assign axi_wready = ~block;

    // AXI Input Registers (CLK Domain)
    always @(posedge CLK or posedge RST) // Use primary posedge reset RST
    begin : SINGLE_SHOT
        if(RST == 1'b1) begin // Active high reset
            waddr <= 32'b0;
            raddr <= 32'b0;
            wdata <= 32'b0;
			wstrb <= 4'b0;
            wassert <= 2'b00;
            rassert <= 1'b0;
        end else begin
            // Write Address Logic
            if(axi_bvalid || block) begin // Wait if blocked or response pending
                waddr <= waddr;
				wstrb <= wstrb;
                wassert[0] <= 1'b0;
            end else if(axi_awvalid && axi_awready) begin // Capture address when valid and ready
                waddr <= axi_awaddr;
				wstrb <= axi_wstrb;
                wassert[0] <= 1'b1;
            end else begin // Hold otherwise
                waddr <= waddr;
				wstrb <= wstrb;
                wassert[0] <= wassert[0];
            end

            // Write Data Logic
            if(axi_bvalid || block) begin // Wait if blocked or response pending
                wdata <= wdata;
                wassert[1] <= 1'b0;
            end else if(axi_wvalid && axi_wready) begin // Capture data when valid and ready
                wdata <= axi_wdata;
                wassert[1] <= 1'b1;
            end else begin // Hold otherwise
                wdata <= wdata;
                wassert[1] <= wassert[1];
            end

            // Read Address Logic
            if(axi_rvalid || block) begin // Wait if blocked or response pending
                raddr <= raddr;
                rassert <= 1'b0;
            end else if(axi_arvalid && axi_arready) begin // Capture address when valid and ready
                raddr <= axi_araddr;
                rassert <= 1'b1;
            end else begin // Hold otherwise
                raddr <= raddr;
                rassert <= rassert;
            end
        end
    end

    // Delayed Valid Signals (CLK Domain)
	localparam NUM_RET_RVALID = 15;
	wire axi_rvalid_def; // RVALID synchronized from effective_mem_clk domain
	reg [NUM_RET_RVALID-1:0] axi_rvalid_def_reg;
	always @(posedge CLK or posedge RST) begin
        if (RST) axi_rvalid_def_reg <= {NUM_RET_RVALID{1'b0}};
        else axi_rvalid_def_reg <= {axi_rvalid_def_reg[NUM_RET_RVALID-2:0], axi_rvalid_def};
    end
	assign axi_rvalid = axi_rvalid_def_reg[NUM_RET_RVALID-1];

	localparam NUM_RET_BVALID = 15;
	wire axi_bvalid_def; // BVALID synchronized from effective_mem_clk domain
	reg [NUM_RET_BVALID-1:0] axi_bvalid_def_reg;
    always @(posedge CLK or posedge RST) begin
        if (RST) axi_bvalid_def_reg <= {NUM_RET_BVALID{1'b0}};
	    else axi_bvalid_def_reg <= {axi_bvalid_def_reg[NUM_RET_BVALID-2:0], axi_bvalid_def};
    end
	assign axi_bvalid = axi_bvalid_def_reg[NUM_RET_BVALID-1];

    // Clock Domain Crossing (CDC) Synchronizers
    // Outputs from MIG (effective_mem_clk domain) to AXI (CLK domain)
    wire sync_clk1_rdata;
    wire sync_clk1_flags;
    assign sync_clk1_rdata = TEST_MODE ? TEST_CLK : mem_ui_clk; // Source clock for CDC
    assign sync_clk1_flags = TEST_MODE ? TEST_CLK : mem_ui_clk; // Source clock for CDC

	bus_sync_sf #(.impl(1), .sword(32+1)) sync_rdata (
        .CLK1(sync_clk1_rdata), // Source Clock (MIG/Test)
        .CLK2(CLK),             // Destination Clock (AXI)
        .RST(RST),              // Primary Reset
	    .data_in({axi_rdata_o, block_o}),
	    .data_out({axi_rdata, block}) // axi_rdata goes to output, block used internally
    );

	bus_sync_sf #(.impl(1), .sword(2)) sync_flags (
        .CLK1(sync_clk1_flags), // Source Clock (MIG/Test)
        .CLK2(CLK),             // Destination Clock (AXI)
        .RST(RST),              // Primary Reset
	    .data_in({axi_bvalid_o, axi_rvalid_o}),
	    .data_out({axi_bvalid_def, axi_rvalid_def}) // Internal delayed valids
    );

    // Inputs from AXI (CLK domain) to MIG (effective_mem_clk domain)
    wire [31:0] waddr_o, raddr_o; // Synchronized address signals
    wire [31:0] wdata_o;         // Synchronized write data
	wire [3:0] wstrb_o;         // Synchronized write strobes
    wire [1:0] wassert_def;     // Synchronized write assert flags (intermediate)
    wire rassert_def;           // Synchronized read assert flag (intermediate)
	wire axi_rready_o;          // Synchronized RREADY
	wire axi_bready_o;          // Synchronized BREADY

    wire sync_clk2_odata;
    wire sync_clk2_flagso;
    assign sync_clk2_odata = TEST_MODE ? TEST_CLK : mem_ui_clk; // Destination clock for CDC
    assign sync_clk2_flagso = TEST_MODE ? TEST_CLK : mem_ui_clk; // Destination clock for CDC

	bus_sync_sf #(.impl(0), .sword(32+32+32+4+2+1)) sync_odata (
        .CLK1(CLK),                 // Source Clock (AXI)
        .CLK2(sync_clk2_odata),     // Destination Clock (MIG/Test)
        .RST(RST),                  // Primary Reset
	    .data_in({waddr, raddr, wdata, wstrb, wassert, rassert}),
	    .data_out({waddr_o, raddr_o, wdata_o, wstrb_o, wassert_def, rassert_def})
    );

	bus_sync_sf #(.impl(0), .sword(2)) sync_flagso (
        .CLK1(CLK),                 // Source Clock (AXI)
        .CLK2(sync_clk2_flagso),    // Destination Clock (MIG/Test)
        .RST(RST),                  // Primary Reset
	    .data_in({axi_bready, axi_rready}),
	    .data_out({axi_bready_o, axi_rready_o})
    );

    // Assert Signal Delay/Hold Logic (effective_mem_clk domain)
    // These registers sample the synchronized assert signals
    localparam NUM_RET_WASSERT = 20;
	reg [NUM_RET_WASSERT-1:0] wassert_def_reg;
    wire wassert_o; // Final write assert signal used by state machine
	always @(posedge effective_mem_clk or negedge effective_mem_rst_n) begin
        if (~effective_mem_rst_n) wassert_def_reg <= {NUM_RET_WASSERT{1'b0}};
        else wassert_def_reg <= {wassert_def_reg[NUM_RET_WASSERT-2:0], &wassert_def}; // Use AND reduction of synchronized signal
    end
	assign wassert_o = wassert_def_reg[NUM_RET_WASSERT-1];

	localparam NUM_RET_RASSERT = 20;
	reg [NUM_RET_RASSERT-1:0] rassert_def_reg;
    wire rassert_o; // Final read assert signal used by state machine
	always @(posedge effective_mem_clk or negedge effective_mem_rst_n) begin
        if (~effective_mem_rst_n) rassert_def_reg <= {NUM_RET_RASSERT{1'b0}};
	    else rassert_def_reg <= {rassert_def_reg[NUM_RET_RASSERT-2:0], rassert_def}; // Use synchronized signal directly
    end
	assign rassert_o = rassert_def_reg[NUM_RET_RASSERT-1];

    // Main State Machine (effective_mem_clk domain)
	always @ (posedge effective_mem_clk or negedge effective_mem_rst_n) begin
		if (~effective_mem_rst_n) begin // Use DFT-friendly async reset (active low)
			axi_bvalid_o <= 1'b0;
			axi_rvalid_o <= 1'b0;
			axi_rdata_o <= 32'b0;
			is_writting <= 1'b0;
			state <= st0_nothing;
			mem_wdf_wren <= 1'b0;
            mem_wdf_end <= 1'b0;
            mem_en <= 1'b0;
			mem_cmd <= 3'b0;
            mem_addr <= 27'b0;
            mem_wdf_data <= 64'b0;
            mem_wdf_mask <= 8'b0;
			block_o <= 1'b0;
		end else begin
			// Default assignments (combinational logic should handle changes)
            mem_wdf_wren <= 1'b0;
            mem_wdf_end <= 1'b0;
            mem_en <= 1'b0;
            axi_bvalid_o <= axi_bvalid_o; // Hold by default
            axi_rvalid_o <= axi_rvalid_o; // Hold by default
            block_o <= block_o;           // Hold by default

			case (state)
				st0_nothing: begin
                    block_o <= 1'b0; // Ensure block is low in idle
                    axi_bvalid_o <= 1'b0; // Ensure valids are low
                    axi_rvalid_o <= 1'b0;
					if(mem_init_calib_complete == 1'b1) begin
						if(mem_rdy == 1'b1) begin
							if(mem_wdf_rdy == 1'b1) begin // Check WDF ready only if writing
								if(wassert_o == 1'b1) begin // Check synchronized write assert
									state <= st2_CheckRdy;
									mem_cmd <= CMD_WRITE;
									mem_wdf_wren <= 1'b1;
									mem_wdf_end <= 1'b1;
									mem_en <= 1'b1;
									mem_addr <= {waddr_o[29:3], 3'b000}; // Use synchronized address
									mem_wdf_data <= {wdata_o, wdata_o}; // Use synchronized data (assuming 64-bit interface)
									mem_wdf_mask <= {~{wstrb_o & {4{waddr_o[2]}}}, ~{wstrb_o & {4{~waddr_o[2]}}}}; // Use sync strobe/addr
									is_writting <= 1'b1;
								end else if(rassert_o == 1'b1) begin // Check synchronized read assert
									state <= st2_CheckRdy;
									mem_cmd <= CMD_READ;
									mem_en <= 1'b1;
									mem_addr <= {raddr_o[29:3], 3'b000}; // Use synchronized address
									is_writting <= 1'b0;
                                    // Clear write-related signals
                                    mem_wdf_wren <= 1'b0;
                                    mem_wdf_end <= 1'b0;
								end else begin
									state <= st0_nothing; // Stay idle
								end
							end else begin // WDF not ready, can still potentially read
                                if(rassert_o == 1'b1) begin // Check synchronized read assert
									state <= st2_CheckRdy;
									mem_cmd <= CMD_READ;
									mem_en <= 1'b1;
									mem_addr <= {raddr_o[29:3], 3'b000}; // Use synchronized address
									is_writting <= 1'b0;
                                    // Clear write-related signals
                                    mem_wdf_wren <= 1'b0;
                                    mem_wdf_end <= 1'b0;
                                end else begin
                                    state <= st0_nothing; // Stay idle
                                end
                            end
						end
					end
				end
				st2_CheckRdy: begin // Command issued, waiting for mem_rdy to deassert
                    mem_wdf_wren <= 1'b0; // Deassert write strobes after first cycle
                    mem_wdf_end <= 1'b0;
					if