module de10_nano_top_corrected_acn(
    input               FPGA_CLK1_50,
    input               FPGA_CLK2_50,
    input               FPGA_CLK3_50,
    input               FPGA_RESET_N, // Added primary reset input
    inout               HPS_CONV_USB_N,
    output   [14: 0]    HPS_DDR3_ADDR,
    output   [ 2: 0]    HPS_DDR3_BA,
    output              HPS_DDR3_CAS_N,
    output              HPS_DDR3_CK_N,
    output              HPS_DDR3_CK_P,
    output              HPS_DDR3_CKE,
    output              HPS_DDR3_CS_N,
    output   [ 3: 0]    HPS_DDR3_DM,
    inout    [31: 0]    HPS_DDR3_DQ,
    inout    [ 3: 0]    HPS_DDR3_DQS_N,
    inout    [ 3: 0]    HPS_DDR3_DQS_P,
    output              HPS_DDR3_ODT,
    output              HPS_DDR3_RAS_N,
    output              HPS_DDR3_RESET_N,
    input               HPS_DDR3_RZQ,
    output              HPS_DDR3_WE_N,
    output   [ 7: 0]    LED
);
wire hps_fpga_reset_n; // This reset comes from HPS, used internally by soc_system
wire                fpga_clk_50;
assign fpga_clk_50 = FPGA_CLK1_50;

// Instantiate the SOC system - its internal reset connection remains
// Assume soc_system handles its own reset logic correctly internally
// or that hps_fpga_reset_n is intended for logic within soc_system.
soc_system u0(
               .clk_clk(FPGA_CLK1_50),
               // Connect the HPS internal reset input to the signal generated by HPS
               // This assumes the reset port of soc_system is meant to be driven by hps_0_h2f_reset_reset_n
               .reset_reset_n(hps_fpga_reset_n),
               .memory_mem_a(HPS_DDR3_ADDR),
               .memory_mem_ba(HPS_DDR3_BA),
               .memory_mem_ck(HPS_DDR3_CK_P),
               .memory_mem_ck_n(HPS_DDR3_CK_N),
               .memory_mem_cke(HPS_DDR3_CKE),
               .memory_mem_cs_n(HPS_DDR3_CS_N),
               .memory_mem_ras_n(HPS_DDR3_RAS_N),
               .memory_mem_cas_n(HPS_DDR3_CAS_N),
               .memory_mem_we_n(HPS_DDR3_WE_N),
               .memory_mem_reset_n(HPS_DDR3_RESET_N),
               .memory_mem_dq(HPS_DDR3_DQ),
               .memory_mem_dqs(HPS_DDR3_DQS_P),
               .memory_mem_dqs_n(HPS_DDR3_DQS_N),
               .memory_mem_odt(HPS_DDR3_ODT),
               .memory_mem_dm(HPS_DDR3_DM),
               .memory_oct_rzqin(HPS_DDR3_RZQ),
               // HPS outputs its reset signal
               .hps_0_h2f_reset_reset_n(hps_fpga_reset_n)
           );

reg [25: 0] counter;
reg led_level;

// Use the primary input reset FPGA_RESET_N for the FPGA logic (counter and led_level)
// This ensures the asynchronous control is controllable from a primary input.
always @(posedge fpga_clk_50 or negedge FPGA_RESET_N) begin // Use primary reset
    if (~FPGA_RESET_N) begin // Check primary reset condition
        counter <= 26'd0;
        led_level <= 1'b0;
    end
    else if (counter == 26'd24999999) begin // Use explicit width and decimal
        counter <= 26'd0;
        led_level <= ~led_level;
    end
    else begin
        counter <= counter + 1'b1;
    end
end

assign LED[0] = led_level;
// Assign remaining LEDs to a default value if they are not driven elsewhere
assign LED[7:1] = 7'b0;

endmodule