`timescale 1 ns / 1 ns
module altera_pli_streaming_corrected_acn ( // Renamed module
    clk,
    reset_n,
    // Primary input for reset request, adhering to ACNCPI principle
    input resetrequest_in, // Changed from output to input

    source_valid,
    source_data,
    source_ready,
    sink_valid,
    sink_data,
    sink_ready
    // Removed original resetrequest output
);
    parameter PLI_PORT = 50000;
    parameter PURPOSE = 0;
    input clk;
    input reset_n; // Primary input asynchronous reset (Good DFT)
    output reg source_valid;
    output reg [7 : 0] source_data;
    input source_ready;
    input sink_valid;
    input [7 : 0] sink_data;
    output reg sink_ready;
    // output reg resetrequest; // Removed output port

    reg pli_out_valid;
    reg pli_in_ready;
    reg [7 : 0] pli_out_data;

    // Internal flip-flops using primary input reset_n (Correct DFT)
    always @(posedge clk or negedge reset_n) begin
        if (!reset_n) begin
            pli_out_valid <= 1'b0; // Use explicit sizing
            pli_out_data <= 8'b0;  // Use explicit sizing
            pli_in_ready <= 1'b0; // Use explicit sizing
        end
        else begin
            `ifdef MODEL_TECH
            // PLI call - assumes this doesn't violate DFT rules internally
            // Note: PLI calls can sometimes obscure DFT issues, but we assume it's okay here.
            $do_transaction(
                PLI_PORT,
                pli_out_valid,
                source_ready,
                pli_out_data,
                sink_valid,
                pli_in_ready,
                sink_data);
            `else
                // Define behavior when not using PLI simulation model
                // This placeholder retains state, replace with actual hardware behavior if different.
                 pli_out_valid <= pli_out_valid;
                 pli_out_data  <= pli_out_data;
                 pli_in_ready  <= pli_in_ready;
            `endif
        end
    end

    // JTAG interface signals
    wire [7:0] jtag_source_data;
    wire jtag_source_valid;
    wire jtag_sink_ready;
    wire jtag_resetrequest; // Internal signal from JTAG block

    // Instantiate JTAG block (using primary input reset_n - Correct DFT)
    altera_jtag_dc_streaming #(.PURPOSE(PURPOSE)) jtag_dc_streaming (
       .clk(clk),
       .reset_n(reset_n),
       .source_data(jtag_source_data),
       .source_valid(jtag_source_valid),
       .sink_data(sink_data),
       .sink_valid(sink_valid),
       .sink_ready(jtag_sink_ready),
       .resetrequest(jtag_resetrequest) // Output from JTAG block
       );

    // Combinational logic for outputs
    // Corrected logic to select between PLI and JTAG paths based on simulation macro
    always @* begin
      `ifdef MODEL_TECH
        // Use PLI signals during simulation
        source_valid = pli_out_valid;
        source_data = pli_out_data;
        sink_ready = pli_in_ready;
        // resetrequest is now an input (resetrequest_in), not driven here
      `else
        // Use JTAG signals otherwise (e.g., synthesis for hardware)
        source_valid = jtag_source_valid;
        source_data = jtag_source_data;
        sink_ready = jtag_sink_ready;
        // resetrequest is now an input (resetrequest_in), not driven here.
        // The internal jtag_resetrequest signal is generated by the sub-module
        // but does not drive a primary output that could be misused as async reset.
      `endif
    end

endmodule