module shift4_corrected_ffc (
    input wire clk,
    input wire rst_n, // Added synchronous reset
    output reg [3:0] data
);

// Parameters
parameter NP = 21;          // Prescaler ratio (generates enable every NP cycles)
parameter INI = 4'b0001;    // Initial value for data shift register

// Internal signals
wire clk_enable;            // Enable signal generated by prescaler logic
reg load_shift = 0;         // Control signal, becomes 1 after first enable
wire serin;                 // Serial input for the shifter (feedback)
reg [$clog2(NP)-1:0] count = 0; // Counter for prescaler

// Prescaler logic: Generate a single-cycle enable pulse every NP clock cycles
// This replaces the internally generated clock 'clk_pres'
assign clk_enable = (count == NP-1);

always @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
        count <= 0;
    end else begin
        if (clk_enable) begin // Reset counter when enable is asserted
            count <= 0;
        end else begin
            count <= count + 1;
        end
    end
end

// load_shift logic: Set high after the first enable pulse, remains high until reset
// Clocked by the primary clock 'clk' and enabled by 'clk_enable'
always @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
        load_shift <= 0;
    end else if (clk_enable) begin // Only update status on enable pulse
        // Set high only once after reset when the first enable arrives
        if (!load_shift) begin
            load_shift <= 1;
        end
    end
end

// Data shift register logic
// Clocked by the primary clock 'clk' and enabled by 'clk_enable'
always @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
        data <= INI; // Reset data to initial value
    end else if (clk_enable) begin // Update data only when enabled
        // Behavior depends on whether the shift has started (load_shift is high)
        // Uses the value of load_shift determined in the previous cycle (or updated concurrently if non-blocking assignments resolve correctly)
        if (load_shift == 0) begin
            // This condition is met on the first enable pulse after reset
            // Load the initial value (potentially redundant if reset does this, but matches original structure)
            data <= INI;
        end else begin
            // Shift in the feedback bit once load_shift is high (on subsequent enable pulses)
            data <= {data[2:0], serin};
        end
    end
    // If !clk_enable, 'data' register holds its previous value implicitly
end

// Combinational logic for serial feedback
assign serin = data[3];

endmodule