`timescale 1ns / 1ns
`default_nettype none

module tld_zxuno (
   input wire clk50mhz,
   input wire test_mode, // Added test mode input for DFT clock selection
   output wire [2:0] r,
   output wire [2:0] g,
   output wire [2:0] b,
   output wire csync,
   output wire stdn,
   output wire stdnb
   );

   assign stdn = 1'b0;
   assign stdnb = 1'b1;

   reg [1:0] divs = 2'b00;
   wire wssclk, sysclk;
   // wire clk14 = divs[0]; // Original clk14, unused downstream but part of divider
   wire clk7_internal; // Internal clock generated by divider
   wire clk7_mux_out;  // Clock signal selected by test_mode

   // Clock divider logic (generates clock for functional mode)
   assign clk7_internal = divs[1];
   always @(posedge sysclk) begin
      divs <= divs + 1;
   end

   // DFT Clock Mux: Selects system clock during test_mode, internal clock otherwise
   // Assumes 'sysclk' is the desired controllable clock during test mode.
   assign clk7_mux_out = test_mode ? sysclk : clk7_internal;

   // Clock generator instance (treat sysclk as derived from primary input clk50mhz)
   relojes los_relojes_del_sistema (
    .CLKIN_IN(clk50mhz),
    .CLKDV_OUT(wssclk),
    .CLKFX_OUT(sysclk),
    .CLKIN_IBUFG_OUT(), // Assuming unused outputs
    .CLK0_OUT(),        // Assuming unused outputs
    .LOCKED_OUT()       // Assuming unused outputs
    );

   // DUT instance using the DFT-friendly clock
   zxuno la_maquina (
    .clk(clk7_mux_out), // Connect the output of the clock mux
    .wssclk(wssclk),
    .r(r),
    .g(g),
    .b(b),
    .csync(csync)
    );

endmodule